#!/usr/bin/env bash
# ===========================================================================
# VERITAS OS — Quick Setup Script
# Usage: bash setup.sh
# ===========================================================================
set -euo pipefail

# ── Colors ─────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

info()    { echo -e "${BLUE}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*"; }
header()  { echo -e "\n${BOLD}=== $* ===${NC}\n"; }

# ── Guard: run from repo root ──────────────────────────────────────────────
if [ ! -f "pyproject.toml" ] || [ ! -d "veritas_os" ]; then
    error "Run this script from the veritas_os repository root."
    exit 1
fi

header "VERITAS OS Setup"

# ── 1. Check prerequisites ─────────────────────────────────────────────────
header "1/4  Checking prerequisites"

# Python 3.11+
find_python() {
    for cmd in python3.12 python3.11 python3 python; do
        if command -v "$cmd" &>/dev/null; then
            local ver
            ver=$("$cmd" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")' 2>/dev/null || true)
            local major minor
            major=$(echo "$ver" | cut -d. -f1)
            minor=$(echo "$ver" | cut -d. -f2)
            if [ "$major" -eq 3 ] && [ "$minor" -ge 11 ]; then
                echo "$cmd"
                return 0
            fi
        fi
    done
    return 1
}

PYTHON_CMD=$(find_python) || {
    error "Python 3.11+ is required but not found."
    echo "  Install: https://www.python.org/downloads/"
    exit 1
}
success "Python: $($PYTHON_CMD --version 2>&1)"

# Node.js (optional — needed only for the Next.js frontend)
SKIP_FRONTEND=false
if command -v node &>/dev/null; then
    success "Node.js: $(node -v)"
else
    warn "Node.js not found — frontend setup will be skipped."
    SKIP_FRONTEND=true
fi

# pnpm (optional — needed only for the frontend)
if [ "$SKIP_FRONTEND" = false ]; then
    if command -v pnpm &>/dev/null; then
        success "pnpm: $(pnpm -v)"
    elif command -v corepack &>/dev/null; then
        info "Enabling pnpm via corepack..."
        corepack enable
        success "pnpm enabled via corepack"
    else
        warn "pnpm not found — frontend setup will be skipped."
        SKIP_FRONTEND=true
    fi
fi

# uv (optional — used by `make test`)
if command -v uv &>/dev/null; then
    success "uv: $(uv --version 2>&1)"
else
    warn "uv not found — 'make test' will fall back to .venv pytest."
    echo "       Install: https://docs.astral.sh/uv/"
fi

# ── 2. Python virtual environment ──────────────────────────────────────────
header "2/4  Setting up Python environment"

CREATE_VENV=true
if [ -d ".venv" ] && [ -x ".venv/bin/python" ]; then
    info "Existing .venv detected."
    read -rp "  Recreate virtual environment? [y/N] " ans
    if [[ ! "$ans" =~ ^[Yy] ]]; then
        CREATE_VENV=false
    fi
fi

if [ "$CREATE_VENV" = true ]; then
    rm -rf .venv
    info "Creating virtual environment..."
    $PYTHON_CMD -m venv .venv
fi

info "Upgrading pip..."
.venv/bin/pip install --upgrade pip -q

info "Installing runtime dependencies..."
.venv/bin/pip install -r veritas_os/requirements.txt -q
success "Runtime dependencies installed."

info "Installing development dependencies (pytest, coverage, etc.)..."
.venv/bin/pip install pytest pytest-cov pytest-asyncio httpx -q
success "Development dependencies installed."

# ── 3. Environment configuration ───────────────────────────────────────────
header "3/4  Configuring environment"

WRITE_ENV=true
if [ -f ".env" ]; then
    info "Existing .env file detected."
    read -rp "  Overwrite with a new .env? [y/N] " ans
    if [[ ! "$ans" =~ ^[Yy] ]]; then
        WRITE_ENV=false
        info "Keeping existing .env."
    fi
fi

if [ "$WRITE_ENV" = true ]; then
    # Generate random secrets
    API_SECRET=$(.venv/bin/python -c "import secrets; print(secrets.token_urlsafe(48))")
    API_KEY="veritas-dev-$(.venv/bin/python -c "import secrets; print(secrets.token_hex(8))")"

    cat > .env << ENVEOF
# ==========================================================
# VERITAS OS — Environment Configuration
# Generated by setup.sh on $(date '+%Y-%m-%d %H:%M:%S' 2>/dev/null || date)
# ==========================================================

# --- LLM Provider ---
# Supported: "openai", "anthropic"
LLM_PROVIDER=openai
LLM_MODEL=gpt-4.1-mini
# OPENAI_API_KEY=sk-...
# ANTHROPIC_API_KEY=sk-ant-...

# --- VERITAS API ---
VERITAS_API_KEY=${API_KEY}
VERITAS_API_SECRET=${API_SECRET}
VERITAS_MAX_REQUEST_BODY_SIZE=10485760

# --- CORS ---
VERITAS_CORS_ALLOW_ORIGINS=http://localhost:3000,http://127.0.0.1:3000

# --- Frontend BFF (server-only) ---
# Keep BFF routing on the server side; do not expose API base URLs via
# NEXT_PUBLIC_* variables.
VERITAS_API_BASE_URL=http://localhost:8000

# --- Production profile hardening ---
# In real production deployments, explicitly set:
# VERITAS_ENV=production
# This enables strict CSP defaults and startup fail-fast checks.
ENVEOF

    chmod 600 .env
    success ".env file created with auto-generated secrets (permissions: 600)."
    warn "Edit .env to set your OPENAI_API_KEY (or ANTHROPIC_API_KEY) before starting."
fi

# ── 4. Frontend setup ──────────────────────────────────────────────────────
if [ "$SKIP_FRONTEND" = false ]; then
    header "4/4  Setting up Frontend"
    info "Installing frontend dependencies (pnpm install)..."
    pnpm install
    success "Frontend dependencies installed."
else
    header "4/4  Frontend setup skipped"
    info "Install Node.js 20+ and pnpm, then run: pnpm install"
fi

# ── Summary ────────────────────────────────────────────────────────────────
header "Setup Complete!"

echo -e "${GREEN}${BOLD}VERITAS OS is ready to go.${NC}"
echo ""
echo "Quick reference:"
echo ""
echo "  Start backend:         ${BLUE}make dev${NC}"
if [ "$SKIP_FRONTEND" = false ]; then
echo "  Start frontend:        ${BLUE}make dev-frontend${NC}"
echo "  Start both:            ${BLUE}make dev-all${NC}"
fi
echo "  Start via Docker:      ${BLUE}make up${NC}"
echo "  Run tests:             ${BLUE}make test${NC}"
echo "  Health check:          ${BLUE}make health${NC}"
echo "  Swagger UI:            ${BLUE}http://localhost:8000/docs${NC}"
echo ""
echo "  Don't forget to set your LLM API key in .env first!"
echo ""
