import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import DecisionConsolePage from "./page";

describe("DecisionConsolePage", () => {
  afterEach(() => {
    vi.restoreAllMocks();
  });

  it("renders pipeline stages in fixed order", () => {
    render(<DecisionConsolePage />);

    expect(screen.getByText("1.", { exact: false })).toBeInTheDocument();
    expect(screen.getByRole("button", { name: /Evidence/i })).toBeInTheDocument();
    expect(screen.getByRole("button", { name: /TrustLog/i })).toBeInTheDocument();
    expect(screen.getByRole("button", { name: /Input/i })).toBeInTheDocument();
  });

  it("shows sample QA fixtures in empty state", () => {
    render(<DecisionConsolePage />);
    expect(screen.getByText("Sample QA fixtures")).toBeInTheDocument();
    expect(screen.getByText(/最低条件は何か/)).toBeInTheDocument();
    expect(screen.getByText(/FujiGate と Value Core の責務を分離/)).toBeInTheDocument();
  });


  it("renders structured sections from decide response", async () => {
    vi.spyOn(global, "fetch").mockResolvedValue({
      ok: true,
      status: 200,
      json: async () => ({
        ok: true,
        error: null,
        request_id: "req-001",
        version: "1.0",
        decision_status: "allow",
        rejection_reason: null,
        chosen: { id: "a1" },
        alternatives: [{ id: "a1" }],
        options: [{ id: "a1" }],
        fuji: { decision_status: "allow" },
        gate: { decision_status: "allow" },
        evidence: [{ source: "doc", snippet: "s", confidence: 0.9 }],
        critique: [],
        debate: [],
        telos_score: 0.9,
        values: { utility: 0.8 },
        plan: null,
        planner: null,
        persona: {},
        memory_citations: [{ id: "m1" }],
        memory_used_count: 1,
        trust_log: null,
        extras: { raw: true },
        meta: {},
        ai_disclosure: "This content was generated by an AI system.",
        regulation_notice: "EU AI Act Art. 50 compliance notice.",
        wat_integrity: {
          integrity_state: "warning",
          wat_id: "wat_001",
          psid_display: "psid-abcd",
          validation_status: "partial",
          admissibility_state: "review",
          replay_status: "bound",
          revocation_status: "active",
          action_summary: "observe",
        },
        wat_drift_vector: {
          policy: 0.2,
          signature: 0.1,
          observable: 0.4,
          temporal: 0.3,
        },
        wat_operator_summary: {
          integrity_severity: "warning",
          affected_lanes: ["wat_shadow"],
          event_ts: "2026-04-23T12:00:00Z",
          correlation_id: "req-001",
          operator_verbosity: "minimal",
        },
      }),
    } as Response);

    render(<DecisionConsolePage />);
    fireEvent.change(screen.getByLabelText("メッセージ"), {
      target: { value: "A/B test" },
    });

    fireEvent.click(screen.getByRole("button", { name: "送信" }));

    await waitFor(() => {
      expect(screen.getByText(/最終判断:|final decision:/)).toBeInTheDocument();
      expect(screen.getByText(/却下理由|Rejected reasons/)).toBeInTheDocument();
      expect(screen.getByText("Cost-Benefit Analytics")).toBeInTheDocument();
      expect(screen.getByText("Total Token Cost")).toBeInTheDocument();
      expect(screen.getByRole("list", { name: "チャットメッセージ一覧" })).toBeInTheDocument();
      expect(screen.getByText("ユーザー")).toBeInTheDocument();
      expect(screen.getByText("アシスタント")).toBeInTheDocument();
      expect(screen.getByText("WAT Operator Summary (v1 minimal)")).toBeInTheDocument();
      expect(screen.getByText("integrity_severity:")).toBeInTheDocument();
      expect(screen.getByText("warning")).toBeInTheDocument();
      expect(screen.queryByText("Drift Vector Breakdown (expanded)")).not.toBeInTheDocument();
    });
  });

  it("renders only the minimal WAT summary card in default console view", async () => {
    vi.spyOn(global, "fetch").mockResolvedValue({
      ok: true,
      status: 200,
      json: async () => ({
        ok: true,
        error: null,
        request_id: "req-minimal-ui",
        version: "1.0",
        decision_status: "allow",
        rejection_reason: null,
        chosen: { id: "a-min" },
        alternatives: [{ id: "a-min" }],
        options: [{ id: "a-min" }],
        fuji: { decision_status: "allow" },
        gate: { decision_status: "allow" },
        evidence: [],
        critique: [],
        debate: [],
        telos_score: 0.91,
        values: {},
        plan: null,
        planner: null,
        persona: {},
        memory_citations: [],
        memory_used_count: 0,
        trust_log: null,
        extras: {},
        meta: {},
        ai_disclosure: "This content was generated by an AI system.",
        regulation_notice: "EU AI Act Art. 50 compliance notice.",
        wat_operator_summary: {
          integrity_severity: "warning",
          affected_lanes: ["wat_shadow"],
          event_ts: "2026-04-23T12:00:00Z",
          correlation_id: "req-minimal-ui",
          operator_verbosity: "minimal",
          warning_context: "temporal_skew",
          warning_correlation_id: "corr-minimal-ui",
        },
        wat_operator_detail: {
          drift_vector: {
            policy: 0.8,
            signature: 0.7,
            observable: 0.6,
            temporal: 0.5,
          },
          verifier_output_raw: { warning: true },
          historical_drift_trend: [{ t: "2026-04-22T12:00:00Z", score: 0.7 }],
        },
      }),
    } as Response);

    render(<DecisionConsolePage />);
    fireEvent.change(screen.getByLabelText("メッセージ"), {
      target: { value: "minimal view contract" },
    });
    fireEvent.click(screen.getByRole("button", { name: "送信" }));

    await waitFor(() => {
      expect(screen.getByText("WAT Operator Summary (v1 minimal)")).toBeInTheDocument();
      expect(screen.queryByText("Drift Vector Breakdown (expanded)")).not.toBeInTheDocument();
      expect(screen.queryByText("verifier_output_raw")).not.toBeInTheDocument();
      expect(screen.queryByText("historical_drift_trend")).not.toBeInTheDocument();
    });
  });



  it("shows governance drift alert when threshold is exceeded", async () => {
    vi.spyOn(global, "fetch").mockResolvedValue({
      ok: true,
      status: 200,
      json: async () => ({
        ok: true,
        error: null,
        request_id: "req-003",
        version: "1.0",
        decision_status: "modify",
        rejection_reason: null,
        chosen: { id: "a3" },
        alternatives: [{ id: "a3" }],
        options: [{ id: "a3" }],
        fuji: { decision_status: "allow" },
        gate: { decision_status: "modify", risk: 0.8 },
        evidence: [{ source: "doc", snippet: "s", confidence: 0.9 }],
        critique: [],
        debate: [],
        telos_score: 0.6,
        values: { valuecore_drift: 12.5 },
        plan: null,
        planner: null,
        persona: {},
        memory_citations: [],
        memory_used_count: 0,
        trust_log: null,
        extras: {},
        meta: {},
        ai_disclosure: "This content was generated by an AI system.",
        regulation_notice: "EU AI Act Art. 50 compliance notice.",
      }),
    } as Response);

    render(<DecisionConsolePage />);
    fireEvent.change(screen.getByLabelText("メッセージ"), {
      target: { value: "governance drift" },
    });

    fireEvent.click(screen.getByRole("button", { name: "送信" }));

    await waitFor(() => {
      expect(screen.getByRole("button", { name: "1 Issue" })).toBeInTheDocument();
      expect(screen.getByText("Drift Alert")).toBeInTheDocument();
      expect(screen.getByText("ValueCoreの乖離が閾値を超えました。レビューを推奨します。")).toBeInTheDocument();
    });
  });

  it("uses backend provided cost_benefit_analytics when available", async () => {
    vi.spyOn(global, "fetch").mockResolvedValue({
      ok: true,
      status: 200,
      json: async () => ({
        ok: true,
        error: null,
        request_id: "req-002",
        version: "1.0",
        decision_status: "allow",
        rejection_reason: null,
        chosen: { id: "a2", uncertainty: 0.45 },
        alternatives: [{ id: "a2" }],
        options: [{ id: "a2" }],
        fuji: { decision_status: "allow" },
        gate: { decision_status: "allow", risk: 0.4 },
        evidence: [{ source: "doc", snippet: "s", confidence: 0.9 }],
        critique: [{ issue: "x" }],
        debate: [{ stance: "pro" }],
        telos_score: 0.8,
        values: { utility: 0.7 },
        plan: null,
        planner: null,
        persona: {},
        memory_citations: [],
        memory_used_count: 0,
        trust_log: null,
        meta: {},
        ai_disclosure: "This content was generated by an AI system.",
        regulation_notice: "EU AI Act Art. 50 compliance notice.",
        extras: {
          cost_benefit_analytics: {
            steps: [
              {
                name: "Debate",
                executed: true,
                uncertainty_before: 0.45,
                uncertainty_after: 0.28,
                token_cost: 520,
              },
            ],
            total_token_cost: 520,
            uncertainty_reduction: 0.17,
          },
        },
      }),
    } as Response);

    render(<DecisionConsolePage />);
    fireEvent.change(screen.getByLabelText("メッセージ"), {
      target: { value: "A/B test" },
    });

    fireEvent.click(screen.getByRole("button", { name: "送信" }));

    await waitFor(() => {
      expect(screen.getAllByText("Debate").length).toBeGreaterThan(0);
      expect(screen.getAllByText("520").length).toBeGreaterThan(0);
      expect(screen.getAllByText("17.0%").length).toBeGreaterThan(0);
    });
  });

  it("renders FUJI Gate status and expandable steps", async () => {
    vi.spyOn(global, "fetch").mockResolvedValue({
      ok: true,
      status: 200,
      json: async () => ({
        ok: true,
        error: null,
        request_id: "req-004",
        version: "1.0",
        decision_status: "modify",
        rejection_reason: "needs redaction",
        chosen: { id: "a4" },
        alternatives: [{ id: "a4" }],
        options: [{ id: "a4" }],
        fuji: { decision_status: "modify" },
        gate: { decision_status: "modify", risk: 0.65 },
        evidence: [{ source: "doc", snippet: "s", confidence: 0.9 }],
        critique: [{ issue: "x" }],
        debate: [{ stance: "pro" }],
        telos_score: 0.7,
        values: { utility: 0.7 },
        plan: [
          { title: "Mask PII", objective: "Remove personal identifiers" },
        ],
        planner: null,
        persona: {},
        memory_citations: [],
        memory_used_count: 0,
        trust_log: null,
        extras: {},
        meta: {},
        ai_disclosure: "This content was generated by an AI system.",
        regulation_notice: "EU AI Act Art. 50 compliance notice.",
      }),
    } as Response);

    render(<DecisionConsolePage />);
    fireEvent.change(screen.getByLabelText("メッセージ"), {
      target: { value: "step expansion" },
    });

    fireEvent.click(screen.getByRole("button", { name: "送信" }));

    await waitFor(() => {
      expect(screen.getByText("rule hit")).toBeInTheDocument();
      expect(screen.getByText("severity")).toBeInTheDocument();
      expect(screen.getByText("Stage Drilldown")).toBeInTheDocument();
      expect(screen.getByText("Mask PII · Planner generated step", { exact: false })).toBeInTheDocument();
      expect(screen.getByText(/decision_id:/i)).toBeInTheDocument();
      expect(screen.getByText("risky text fragment preview")).toBeInTheDocument();
    });
  });

  it("renders critical integrity state for WAT widget", async () => {
    vi.spyOn(global, "fetch").mockResolvedValue({
      ok: true,
      status: 200,
      json: async () => ({
        ok: true,
        error: null,
        request_id: "req-005",
        version: "1.0",
        decision_status: "modify",
        rejection_reason: null,
        chosen: { id: "a5" },
        alternatives: [{ id: "a5" }],
        options: [{ id: "a5" }],
        fuji: { decision_status: "allow" },
        gate: { decision_status: "modify", risk: 0.7 },
        evidence: [],
        critique: [],
        debate: [],
        telos_score: 0.5,
        values: {},
        plan: null,
        planner: null,
        persona: {},
        memory_citations: [],
        memory_used_count: 0,
        trust_log: null,
        extras: {},
        meta: {},
        ai_disclosure: "This content was generated by an AI system.",
        regulation_notice: "EU AI Act Art. 50 compliance notice.",
        wat_integrity: {
          integrity_state: "critical",
          wat_id: "wat_critical",
          psid_display: "psid-zzzz",
          validation_status: "failed",
          admissibility_state: "blocked",
        },
        wat_operator_summary: {
          integrity_severity: "critical",
          affected_lanes: ["wat_shadow"],
          event_ts: "2026-04-23T12:00:00Z",
          correlation_id: "req-005",
          operator_verbosity: "minimal",
        },
      }),
    } as Response);

    render(<DecisionConsolePage />);
    fireEvent.change(screen.getByLabelText("メッセージ"), {
      target: { value: "critical wat" },
    });
    fireEvent.click(screen.getByRole("button", { name: "送信" }));

    await waitFor(() => {
      expect(screen.getByText("critical")).toBeInTheDocument();
      expect(screen.getByText("req-005")).toBeInTheDocument();
    });
  });

  it("gracefully falls back to legacy meta.wat_shadow payload", async () => {
    vi.spyOn(global, "fetch").mockResolvedValue({
      ok: true,
      status: 200,
      json: async () => ({
        ok: true,
        error: null,
        request_id: "req-006",
        version: "1.0",
        decision_status: "allow",
        rejection_reason: null,
        chosen: { id: "a6" },
        alternatives: [{ id: "a6" }],
        options: [{ id: "a6" }],
        fuji: { decision_status: "allow" },
        gate: { decision_status: "allow", risk: 0.1 },
        evidence: [],
        critique: [],
        debate: [],
        telos_score: 0.8,
        values: {},
        plan: null,
        planner: null,
        persona: {},
        memory_citations: [],
        memory_used_count: 0,
        trust_log: null,
        extras: {},
        meta: {
          wat_shadow: {
            wat_id: "wat_legacy",
            psid_display: "psid-legacy",
            validation_status: "invalid",
            admissibility_state: "non_admissible",
            replay_status: "suspected",
            revocation_status: "active",
            drift_vector: {
              policy_drift: 0.6,
              signature_drift: 0.5,
              observable_drift: 0.4,
              temporal_drift: 0.3,
            },
          },
        },
        ai_disclosure: "This content was generated by an AI system.",
        regulation_notice: "EU AI Act Art. 50 compliance notice.",
      }),
    } as Response);

    render(<DecisionConsolePage />);
    fireEvent.change(screen.getByLabelText("メッセージ"), {
      target: { value: "legacy wat" },
    });
    fireEvent.click(screen.getByRole("button", { name: "送信" }));

    await waitFor(() => {
      expect(screen.getByText("req-006")).toBeInTheDocument();
      expect(screen.queryByText("0.60")).not.toBeInTheDocument();
    });
  });

  it("reveals drift drill-down only in expanded verbosity mode", async () => {
    vi.spyOn(global, "fetch").mockResolvedValue({
      ok: true,
      status: 200,
      json: async () => ({
        ok: true,
        error: null,
        request_id: "req-007",
        version: "1.0",
        decision_status: "allow",
        rejection_reason: null,
        chosen: { id: "a7" },
        alternatives: [{ id: "a7" }],
        options: [{ id: "a7" }],
        fuji: { decision_status: "allow" },
        gate: { decision_status: "allow", risk: 0.1 },
        evidence: [],
        critique: [],
        debate: [],
        telos_score: 0.8,
        values: {},
        plan: null,
        planner: null,
        persona: {},
        memory_citations: [],
        memory_used_count: 0,
        trust_log: null,
        extras: {},
        meta: {},
        wat_drift_vector: {
          policy: 0.6,
          signature: 0.5,
          observable: 0.4,
          temporal: 0.3,
        },
        wat_operator_summary: {
          integrity_severity: "warning",
          affected_lanes: ["wat_shadow"],
          event_ts: "2026-04-23T12:00:00Z",
          correlation_id: "req-007",
          operator_verbosity: "expanded",
        },
        ai_disclosure: "This content was generated by an AI system.",
        regulation_notice: "EU AI Act Art. 50 compliance notice.",
      }),
    } as Response);

    render(<DecisionConsolePage />);
    fireEvent.change(screen.getByLabelText("メッセージ"), {
      target: { value: "expanded wat" },
    });
    fireEvent.click(screen.getByRole("button", { name: "送信" }));

    await waitFor(() => {
      expect(screen.getByText("Drift Vector Breakdown (expanded)")).toBeInTheDocument();
      expect(screen.getByText("0.60")).toBeInTheDocument();
    });
  });

});
