"""Deterministic VERITAS / CAGE Provider03 Phase 3 proof helpers.

This module is intentionally synthetic and side-effect-free.  It projects the
existing VERITAS AML/KYC regulated-action fixture into the source-confirmed
Provider03 contract without importing CAGE or claiming a live CAGE runtime
integration.

The proof keeps distinct hash domains for:
- VERITAS's existing bind-receipt content hash; and
- the CAGE Provider03 ingest digest over the complete receipt.

TrustLog evidence is lineage-only unless an actual witness is generated by a
separate TrustLog path.
"""

from __future__ import annotations

import hashlib
import json
from collections import Counter
from pathlib import Path
from typing import Any, Mapping

from veritas_os.governance.regulated_action_path import (
    RegulatedActionPathResult,
    run_all_regulated_action_scenarios,
)
from veritas_os.security.hash import sha256_of_canonical_json

PHASE3_PROOF_ID = "veritas-cage-provider03-phase3-v1"
PHASE3_SCHEMA_VERSION = "veritas-cage-phase3-evidence-v1"
FIXTURE_ID = "aml_kyc_regulated_action_path_v1"
CAGE_SOURCE_COMMIT = "ecbcce3253cb55c333f47009c40a45dbc5b3a454"
CAGE_PROVIDER03_PATH = "src/integrations/provider_03/provider.py"
TRUSTLOG_PROOF_STATUS = "lineage_only"

PROVIDER03_FIELD_MAP: dict[str, str] = {
    "amount": "magnitude",
    "symbol": "context",
}

VERITAS_OUTCOME_TO_PROVIDER03: dict[str, str] = {
    "commit": "APPROVED",
    "escalate": "ESCALATE",
    "block": "REJECTED",
    "refuse": "REJECTED",
}


class Phase3ProofError(RuntimeError):
    """Raised when the deterministic proof contract is violated."""


def normalize_provider03_payload(
    payload: Mapping[str, Any],
    *,
    field_map: Mapping[str, str] | None = None,
) -> dict[str, Any]:
    """Mirror Provider03 action_context mapping without mutating caller state.

    The current CAGE Provider03 adapter applies caller-declared field mapping
    inside ``action_context``.  Phase 3 uses the agreed compatibility mapping:
    ``amount -> magnitude`` and ``symbol -> context``.
    """

    outbound = dict(payload)
    action_context = payload.get("action_context")
    if not field_map or not isinstance(action_context, dict):
        return outbound

    normalized_context = dict(action_context)
    for source_key, destination_key in field_map.items():
        if source_key in normalized_context:
            normalized_context[destination_key] = normalized_context.pop(source_key)
    outbound["action_context"] = normalized_context
    return outbound


def build_provider03_response(result: RegulatedActionPathResult) -> dict[str, Any]:
    """Project a VERITAS deterministic outcome into Provider03 wire semantics."""

    verdict = VERITAS_OUTCOME_TO_PROVIDER03.get(result.actual_outcome, "REJECTED")
    if result.actual_outcome == "commit":
        code = "veritas.commit_boundary"
        severity = "info"
    elif result.actual_outcome == "escalate":
        code = "veritas.escalation_required"
        severity = "review"
    elif result.actual_outcome in {"block", "refuse"}:
        code = "veritas.bind_blocked"
        severity = "blocked"
    else:
        code = "veritas.unmapped_outcome"
        severity = "blocked"

    finding: dict[str, Any] = {
        "code": code,
        "severity": severity,
        "scenario_name": result.scenario_name,
        "commit_boundary_result": result.commit_boundary_result,
        "bind_receipt_id": result.bind_receipt_id,
        "authority_evidence_id": result.authority_evidence_id,
        "failed_predicate_count": result.failed_predicate_count,
        "stale_predicate_count": result.stale_predicate_count,
        "missing_predicate_count": result.missing_predicate_count,
        "refusal_basis": list(result.refusal_basis),
        "escalation_basis": list(result.escalation_basis),
    }
    if result.actual_outcome not in VERITAS_OUTCOME_TO_PROVIDER03:
        finding["unmapped_outcome"] = result.actual_outcome

    return {"verdict": verdict, "findings": [finding]}


def project_provider03_validation_result(response: Mapping[str, Any]) -> dict[str, Any]:
    """Project Provider03 response semantics as confirmed by the CAGE adapter."""

    verdict = str(response.get("verdict", "")).upper()
    raw_findings = response.get("findings", [])
    findings = list(raw_findings) if isinstance(raw_findings, list) else []

    if verdict == "APPROVED":
        return {
            "admitted": True,
            "findings": findings,
            "error": None,
        }

    if verdict == "ESCALATE":
        review_marker = {
            "code": "provider_03.escalate",
            "severity": "review",
            "message": "Provider 03 returned ESCALATE — requires human approval",
            "needs_human_review": True,
            "provider_03_verdict": "ESCALATE",
            "provider_03_findings": findings,
        }
        return {
            "admitted": False,
            "findings": [review_marker, *findings],
            "error": None,
        }

    # REJECTED, unknown, and missing verdicts fail closed.
    return {
        "admitted": False,
        "findings": findings,
        "error": None,
    }


def project_provider03_endpoint_failure(error: str) -> dict[str, Any]:
    """Represent the confirmed fail-closed Provider03 endpoint-error contract."""

    return {
        "admitted": False,
        "findings": [
            {
                "code": "ENDPOINT_ERROR",
                "severity": "blocked",
                "message": error,
            }
        ],
        "error": error,
    }


def build_bind_receipt_sidecar(result: RegulatedActionPathResult) -> dict[str, Any]:
    """Reconstruct the existing deterministic VERITAS bind receipt as a sidecar."""

    body: dict[str, Any] = {
        "bind_receipt_id": result.bind_receipt_id,
        "action_contract_id": result.action_contract_id,
        "authority_evidence_id": result.authority_evidence_id,
        "authority_evidence_hash": str(result.metadata.get("authority_evidence_hash", "")),
        "commit_boundary_result": result.commit_boundary_result,
    }
    receipt = dict(body)
    receipt["bind_receipt_hash"] = sha256_of_canonical_json(body)
    return receipt


def jcs_canonicalize_phase3(payload: Any) -> bytes:
    """Canonicalize the JSON subset used by Phase 3 in RFC 8785-compatible form.

    Phase 3 artifacts intentionally contain only JSON strings, integers,
    booleans, nulls, lists, and string-keyed objects.  Floating-point values
    are rejected rather than approximating ECMAScript number serialization.

    For this bounded fixture domain, the emitted representation follows JCS:
    UTF-8, no insignificant whitespace, unescaped Unicode where permitted,
    and object keys sorted by UTF-16 code units.
    """

    def _string(value: str) -> str:
        return json.dumps(value, ensure_ascii=False, separators=(",", ":"))

    def _sort_key(value: str) -> bytes:
        return value.encode("utf-16be", "surrogatepass")

    def _render(value: Any) -> str:
        if value is None:
            return "null"
        if value is True:
            return "true"
        if value is False:
            return "false"
        if isinstance(value, int) and not isinstance(value, bool):
            return str(value)
        if isinstance(value, float):
            raise TypeError(
                "Phase 3 JCS proof rejects floats; use integer or string fixture values"
            )
        if isinstance(value, str):
            return _string(value)
        if isinstance(value, (list, tuple)):
            return "[" + ",".join(_render(item) for item in value) + "]"
        if isinstance(value, Mapping):
            if not all(isinstance(key, str) for key in value):
                raise TypeError("Phase 3 JCS objects require string keys")
            parts = [
                f"{_string(key)}:{_render(value[key])}"
                for key in sorted(value, key=_sort_key)
            ]
            return "{" + ",".join(parts) + "}"
        raise TypeError(f"Unsupported Phase 3 JCS type: {type(value).__name__}")

    return _render(payload).encode("utf-8")


def cage_ingested_bind_receipt_digest(receipt: Mapping[str, Any]) -> str:
    """Compute the Provider03-style JCS SHA-256 ingest digest."""

    return hashlib.sha256(jcs_canonicalize_phase3(receipt)).hexdigest()


def build_phase3_evidence_artifact(
    result: RegulatedActionPathResult,
    provider03_response: Mapping[str, Any],
    validation_projection: Mapping[str, Any],
    bind_receipt: Mapping[str, Any],
    cage_receipt_digest: str,
) -> dict[str, Any]:
    """Build the deterministic, reviewer-facing synthetic evidence artifact."""

    return {
        "schema_version": PHASE3_SCHEMA_VERSION,
        "fixture_id": FIXTURE_ID,
        "scenario_name": result.scenario_name,
        "cage_thread_id": f"phase3::{result.scenario_name}",
        "veritas_outcome": result.actual_outcome,
        "provider03_verdict": str(provider03_response.get("verdict", "")),
        "cage_admitted": bool(validation_projection.get("admitted", False)),
        "bind_receipt_id": result.bind_receipt_id,
        "veritas_bind_receipt_hash": str(bind_receipt["bind_receipt_hash"]),
        "cage_ingested_bind_receipt_digest": cage_receipt_digest,
        "authority_evidence_id": result.authority_evidence_id,
        "trustlog_proof_status": TRUSTLOG_PROOF_STATUS,
        "trustlog_lineage_ref": result.trustlog_lineage_ref,
        "evidence_chain_status": "fixture_linked",
    }


def phase3_evidence_seal_hash(evidence_artifact: Mapping[str, Any]) -> str:
    """Return the deterministic SHA-256 seal over the Phase 3 JCS artifact."""

    return hashlib.sha256(jcs_canonicalize_phase3(evidence_artifact)).hexdigest()


def build_phase3_scenario_proof(
    result: RegulatedActionPathResult,
) -> dict[str, Any]:
    """Build one deterministic Phase 3 scenario proof."""

    if result.actual_outcome != result.expected_outcome:
        raise Phase3ProofError(
            f"{result.scenario_name}: expected {result.expected_outcome!r}, "
            f"got {result.actual_outcome!r}"
        )

    provider03_response = build_provider03_response(result)
    validation_projection = project_provider03_validation_result(provider03_response)
    bind_receipt = build_bind_receipt_sidecar(result)
    cage_receipt_digest = cage_ingested_bind_receipt_digest(bind_receipt)
    evidence_artifact = build_phase3_evidence_artifact(
        result,
        provider03_response,
        validation_projection,
        bind_receipt,
        cage_receipt_digest,
    )
    seal_hash = phase3_evidence_seal_hash(evidence_artifact)

    return {
        "scenario_name": result.scenario_name,
        "expected_outcome": result.expected_outcome,
        "actual_outcome": result.actual_outcome,
        "provider03_response": provider03_response,
        "validation_projection": validation_projection,
        "bind_receipt": bind_receipt,
        "hash_domains": {
            "veritas_bind_receipt_hash": {
                "value": bind_receipt["bind_receipt_hash"],
                "input": "bind receipt body before bind_receipt_hash is added",
                "canonicalization": "VERITAS canonical JSON",
            },
            "cage_ingested_bind_receipt_digest": {
                "value": cage_receipt_digest,
                "input": "complete bind receipt including bind_receipt_hash",
                "canonicalization": "RFC 8785 JCS-compatible Phase 3 subset",
            },
        },
        "trustlog": {
            "proof_status": TRUSTLOG_PROOF_STATUS,
            "lineage_ref": result.trustlog_lineage_ref,
            "witness_hash": None,
        },
        "evidence_artifact": evidence_artifact,
        "evidence_seal": {
            "thread_id": evidence_artifact["cage_thread_id"],
            "seal_hash": seal_hash,
        },
    }


def build_phase3_proof_bundle() -> dict[str, Any]:
    """Build the deterministic seven-scenario proof bundle."""

    results = run_all_regulated_action_scenarios()
    if len(results) != 7:
        raise Phase3ProofError(f"expected 7 AML/KYC scenarios, found {len(results)}")

    scenario_proofs = [build_phase3_scenario_proof(result) for result in results]
    verdict_counts = Counter(
        proof["provider03_response"]["verdict"] for proof in scenario_proofs
    )
    expected_counts = {"APPROVED": 1, "ESCALATE": 1, "REJECTED": 5}
    observed_counts = {
        verdict: verdict_counts.get(verdict, 0)
        for verdict in ("APPROVED", "ESCALATE", "REJECTED")
    }
    if observed_counts != expected_counts:
        raise Phase3ProofError(
            f"unexpected Provider03 verdict counts: {observed_counts!r}"
        )

    return {
        "manifest": {
            "proof_id": PHASE3_PROOF_ID,
            "fixture_id": FIXTURE_ID,
            "proof_mode": "synthetic_deterministic_side_effect_free",
            "scenario_count": 7,
            "expected_primary_results": expected_counts,
            "observed_primary_results": observed_counts,
            "cage_contract_surface": {
                "source_commit": CAGE_SOURCE_COMMIT,
                "provider03_path": CAGE_PROVIDER03_PATH,
                "adapter": "Provider03NormativeProvider",
                "validate_path": "/validate",
                "verdicts": ["APPROVED", "ESCALATE", "REJECTED"],
                "field_map": dict(PROVIDER03_FIELD_MAP),
                "field_map_mode": "explicit_caller_declared",
            },
            "canonicalization": "RFC8785-JCS-compatible-bounded-fixture-subset",
            "hash_algorithm": "SHA-256",
            "trustlog_mode": TRUSTLOG_PROOF_STATUS,
            "live_external_effects": False,
            "production_claim": False,
            "live_cage_runtime_claim": False,
        },
        "scenarios": scenario_proofs,
    }


def build_replay_report(
    first: Mapping[str, Any],
    second: Mapping[str, Any],
) -> dict[str, Any]:
    """Compare two independently built deterministic proof bundles."""

    first_by_name = {
        item["scenario_name"]: item for item in first.get("scenarios", [])
    }
    second_by_name = {
        item["scenario_name"]: item for item in second.get("scenarios", [])
    }
    names = sorted(set(first_by_name) | set(second_by_name))
    scenarios: list[dict[str, Any]] = []

    for name in names:
        left = first_by_name.get(name)
        right = second_by_name.get(name)
        if left is None or right is None:
            scenarios.append(
                {
                    "scenario_name": name,
                    "overall_replay_match": False,
                    "reason": "scenario missing from one replay",
                }
            )
            continue

        report = {
            "scenario_name": name,
            "outcome_match": left["actual_outcome"] == right["actual_outcome"],
            "provider03_verdict_match": (
                left["provider03_response"]["verdict"]
                == right["provider03_response"]["verdict"]
            ),
            "bind_receipt_hash_match": (
                left["bind_receipt"]["bind_receipt_hash"]
                == right["bind_receipt"]["bind_receipt_hash"]
            ),
            "cage_receipt_digest_match": (
                left["hash_domains"]["cage_ingested_bind_receipt_digest"]["value"]
                == right["hash_domains"]["cage_ingested_bind_receipt_digest"]["value"]
            ),
            "evidence_seal_match": (
                left["evidence_seal"]["seal_hash"]
                == right["evidence_seal"]["seal_hash"]
            ),
        }
        report["overall_replay_match"] = all(
            value for key, value in report.items() if key.endswith("_match")
        )
        scenarios.append(report)

    return {
        "proof_id": PHASE3_PROOF_ID,
        "scenario_count": len(scenarios),
        "scenarios": scenarios,
        "overall_replay_match": (
            len(scenarios) == 7
            and all(item.get("overall_replay_match") is True for item in scenarios)
        ),
    }


def build_negative_test_report(bundle: Mapping[str, Any]) -> dict[str, Any]:
    """Run deterministic fail-closed and tamper-sensitivity proof checks."""

    scenarios = {item["scenario_name"]: item for item in bundle.get("scenarios", [])}
    checks: list[dict[str, Any]] = []

    def _record(name: str, passed: bool, detail: str) -> None:
        checks.append({"name": name, "passed": bool(passed), "detail": detail})

    unknown = project_provider03_validation_result(
        {"verdict": "MAYBE", "findings": [{"code": "synthetic.unknown"}]}
    )
    _record(
        "unknown_verdict_fails_closed",
        unknown["admitted"] is False,
        "Unknown Provider03 verdict must not admit.",
    )

    missing = project_provider03_validation_result({"findings": []})
    _record(
        "missing_verdict_fails_closed",
        missing["admitted"] is False,
        "Missing Provider03 verdict must not admit.",
    )

    endpoint = project_provider03_endpoint_failure("synthetic endpoint failure")
    _record(
        "endpoint_failure_fails_closed",
        endpoint["admitted"] is False
        and endpoint["findings"][0]["code"] == "ENDPOINT_ERROR",
        "Synthetic endpoint failure remains denied with ENDPOINT_ERROR.",
    )

    legacy_payload = {
        "action_context": {
            "amount": 100000,
            "symbol": "AAPL",
            "currency": "USD",
        }
    }
    before = json.loads(json.dumps(legacy_payload))
    normalized = normalize_provider03_payload(
        legacy_payload,
        field_map=PROVIDER03_FIELD_MAP,
    )
    _record(
        "action_context_normalization",
        normalized["action_context"]
        == {"magnitude": 100000, "context": "AAPL", "currency": "USD"},
        "Legacy amount/symbol map to magnitude/context.",
    )
    _record(
        "normalization_does_not_mutate_caller",
        legacy_payload == before,
        "Caller payload is unchanged after normalization.",
    )

    approved = scenarios.get("scenario_a_allowed_internal_escalation")
    if approved is not None:
        receipt = dict(approved["bind_receipt"])
        original_digest = cage_ingested_bind_receipt_digest(receipt)
        mutated_receipt = dict(receipt)
        mutated_receipt["commit_boundary_result"] = "block"
        mutated_digest = cage_ingested_bind_receipt_digest(mutated_receipt)
        _record(
            "bind_receipt_mutation_changes_digest",
            original_digest != mutated_digest,
            "Governance-significant receipt mutation changes CAGE ingest digest.",
        )

        evidence = dict(approved["evidence_artifact"])
        original_seal = phase3_evidence_seal_hash(evidence)
        mutated_evidence = dict(evidence)
        mutated_evidence["provider03_verdict"] = "REJECTED"
        mutated_seal = phase3_evidence_seal_hash(mutated_evidence)
        _record(
            "evidence_mutation_changes_seal",
            original_seal != mutated_seal,
            "Governance-significant evidence mutation changes seal hash.",
        )

    missing_authority = scenarios.get("scenario_e_missing_authority")
    _record(
        "missing_authority_rejected",
        bool(
            missing_authority
            and missing_authority["provider03_response"]["verdict"] == "REJECTED"
            and missing_authority["validation_projection"]["admitted"] is False
        ),
        "Existing missing-authority fixture remains fail-closed.",
    )

    missing_approval = scenarios.get(
        "scenario_f_high_irreversibility_without_human_approval"
    )
    _record(
        "missing_human_approval_rejected",
        bool(
            missing_approval
            and missing_approval["provider03_response"]["verdict"] == "REJECTED"
            and missing_approval["validation_projection"]["admitted"] is False
        ),
        "Existing missing-approval fixture remains fail-closed.",
    )

    stale = scenarios.get("scenario_d_stale_sanctions_screening")
    stale_marker = []
    if stale:
        stale_marker = [
            finding
            for finding in stale["validation_projection"]["findings"]
            if finding.get("needs_human_review") is True
        ]
    _record(
        "stale_evidence_escalates_to_human_review",
        bool(
            stale
            and stale["provider03_response"]["verdict"] == "ESCALATE"
            and stale["validation_projection"]["admitted"] is False
            and stale_marker
        ),
        "Stale-evidence fixture remains ESCALATE/DEFER rather than APPROVED.",
    )

    return {
        "proof_id": PHASE3_PROOF_ID,
        "checks": checks,
        "passed": all(check["passed"] for check in checks),
    }


def write_phase3_artifacts(
    output_dir: Path,
    *,
    first_bundle: Mapping[str, Any] | None = None,
    second_bundle: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    """Write deterministic reviewer-facing Phase 3 artifacts."""

    first = dict(first_bundle or build_phase3_proof_bundle())
    second = dict(second_bundle or build_phase3_proof_bundle())
    replay_report = build_replay_report(first, second)
    negative_report = build_negative_test_report(first)
    if not replay_report["overall_replay_match"]:
        raise Phase3ProofError("deterministic replay mismatch")
    if not negative_report["passed"]:
        raise Phase3ProofError("negative proof check failed")

    output_dir.mkdir(parents=True, exist_ok=True)
    scenario_dir = output_dir / "scenarios"
    scenario_dir.mkdir(parents=True, exist_ok=True)

    def _write(path: Path, payload: Any) -> None:
        path.write_text(
            json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )

    _write(output_dir / "manifest.json", first["manifest"])
    for scenario in first["scenarios"]:
        _write(scenario_dir / f"{scenario['scenario_name']}.json", scenario)
    _write(output_dir / "replay_report.json", replay_report)
    _write(output_dir / "negative_test_report.json", negative_report)

    summary = {
        "proof_id": PHASE3_PROOF_ID,
        "scenario_count": len(first["scenarios"]),
        "observed_primary_results": first["manifest"]["observed_primary_results"],
        "overall_replay_match": replay_report["overall_replay_match"],
        "negative_tests_passed": negative_report["passed"],
        "live_external_effects": False,
        "production_claim": False,
        "live_cage_runtime_claim": False,
    }
    _write(output_dir / "summary.json", summary)
    return summary
