import { renderHook, act } from "@testing-library/react";
import { describe, expect, it, vi, beforeEach, afterEach } from "vitest";
import { useDecide } from "./useDecide";

type DecidePayload = Record<string, unknown>;

function buildDecidePayload(requestId: string, decision: string): DecidePayload {
  return {
    ok: true,
    error: null,
    request_id: requestId,
    version: "test",
    chosen: {},
    alternatives: [],
    options: [],
    decision_status: "allow",
    rejection_reason: null,
    values: null,
    telos_score: 0.5,
    fuji: {},
    gate: {
      risk: 0.1,
      telos_score: 0.5,
      decision_status: "allow",
      modifications: [],
    },
    evidence: [],
    critique: [],
    debate: [],
    extras: { decision },
    meta: {},
    plan: null,
    planner: null,
    persona: {},
    memory_citations: [],
    memory_used_count: 0,
    trust_log: null,
    ai_disclosure: "This content was generated by an AI system.",
    regulation_notice: "EU AI Act Art. 50 compliance notice.",
  };
}

function createDeferred<T>() {
  let resolve!: (value: T) => void;
  let reject!: (reason?: unknown) => void;
  const promise = new Promise<T>((res, rej) => {
    resolve = res;
    reject = rej;
  });
  return { promise, resolve, reject };
}

describe("useDecide", () => {
  beforeEach(() => {
    vi.restoreAllMocks();
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it("aborts an in-flight request when a new runDecision starts", async () => {
    const first = createDeferred<Response>();
    const secondPayload = buildDecidePayload("req-2", "latest");

    const fetchMock = vi
      .fn<typeof fetch>()
      .mockImplementationOnce((_input, init) => {
        const signal = init?.signal as AbortSignal;
        return new Promise<Response>((_resolve, reject) => {
          signal.addEventListener("abort", () => {
            reject(new DOMException("Aborted", "AbortError"));
          });
          void first.promise;
        });
      })
      .mockResolvedValueOnce(
        new Response(JSON.stringify(secondPayload), {
          status: 200,
          headers: { "Content-Type": "application/json" },
        }),
      );

    vi.stubGlobal("fetch", fetchMock);

    const setQuery = vi.fn();
    const setResult = vi.fn();
    const setChatMessages = vi.fn();

    const { result } = renderHook(() =>
      useDecide({
        t: (_ja, en) => en,
        tk: (key) => key,
        query: "q",
        setQuery,
        setResult,
        setChatMessages,
      }),
    );

    await act(async () => {
      void result.current.runDecision("first");
      await Promise.resolve();
      await result.current.runDecision("second");
    });

    expect(fetchMock).toHaveBeenCalledTimes(2);
    expect(setResult).toHaveBeenCalledWith(secondPayload);
  });



  it("sanitizes non-ok error response and does not expose body text", async () => {
    const sensitiveBody = '{"debug":"stack trace"}';
    const fetchMock = vi.fn<typeof fetch>().mockResolvedValue(
      new Response(sensitiveBody, {
        status: 500,
        headers: { "Content-Type": "application/json" },
      }),
    );

    vi.stubGlobal("fetch", fetchMock);

    const setQuery = vi.fn();
    const setResult = vi.fn();
    const setChatMessages = vi.fn();

    const { result } = renderHook(() =>
      useDecide({
        t: (_ja, en) => en,
        tk: (key) => key,
        query: "q",
        setQuery,
        setResult,
        setChatMessages,
      }),
    );

    await act(async () => {
      await result.current.runDecision("question");
    });

    expect(result.current.error).toBe("serverError");
    expect(result.current.error).not.toContain("stack trace");
    expect(setResult).toHaveBeenCalledWith(null);
  });
  it("sets error when query is empty", async () => {
    const setQuery = vi.fn();
    const setResult = vi.fn();
    const setChatMessages = vi.fn();

    const { result } = renderHook(() =>
      useDecide({
        t: (_ja, en) => en,
        tk: (key) => key,
        query: "",
        setQuery,
        setResult,
        setChatMessages,
      }),
    );

    await act(async () => {
      await result.current.runDecision("   ");
    });

    expect(result.current.error).toBe("queryRequired");
    expect(result.current.executionStatus).toBe("failed");
  });

  it("handles 401 auth error response", async () => {
    const fetchMock = vi.fn<typeof fetch>().mockResolvedValue(
      new Response('{"error":"unauthorized"}', {
        status: 401,
        headers: { "Content-Type": "application/json" },
      }),
    );
    vi.stubGlobal("fetch", fetchMock);

    const setResult = vi.fn();
    const setChatMessages = vi.fn();

    const { result } = renderHook(() =>
      useDecide({
        t: (_ja, en) => en,
        tk: (key) => key,
        query: "test",
        setQuery: vi.fn(),
        setResult,
        setChatMessages,
      }),
    );

    await act(async () => {
      await result.current.runDecision("test query");
    });

    expect(result.current.error).toBe("authError");
    expect(result.current.executionStatus).toBe("failed");
    expect(setResult).toHaveBeenCalledWith(null);
  });

  it("handles 503 service unavailable response", async () => {
    const fetchMock = vi.fn<typeof fetch>().mockResolvedValue(
      new Response('{"error":"unavailable"}', {
        status: 503,
        headers: { "Content-Type": "application/json" },
      }),
    );
    vi.stubGlobal("fetch", fetchMock);

    const setResult = vi.fn();
    const setChatMessages = vi.fn();

    const { result } = renderHook(() =>
      useDecide({
        t: (_ja, en) => en,
        tk: (key) => key,
        query: "test",
        setQuery: vi.fn(),
        setResult,
        setChatMessages,
      }),
    );

    await act(async () => {
      await result.current.runDecision("test query");
    });

    expect(result.current.error).toBe("serviceUnavailable");
    expect(result.current.executionStatus).toBe("failed");
    expect(setResult).toHaveBeenCalledWith(null);
  });

  it("handles schema validation failure", async () => {
    const invalidPayload = { not_a_valid: "response" };
    const fetchMock = vi.fn<typeof fetch>().mockResolvedValue(
      new Response(JSON.stringify(invalidPayload), {
        status: 200,
        headers: { "Content-Type": "application/json" },
      }),
    );
    vi.stubGlobal("fetch", fetchMock);

    const setResult = vi.fn();
    const setChatMessages = vi.fn();

    const { result } = renderHook(() =>
      useDecide({
        t: (_ja, en) => en,
        tk: (key) => key,
        query: "test",
        setQuery: vi.fn(),
        setResult,
        setChatMessages,
      }),
    );

    await act(async () => {
      await result.current.runDecision("test query");
    });

    expect(result.current.error).toBe("schemaMismatch");
    expect(result.current.executionStatus).toBe("failed");
    expect(setResult).toHaveBeenCalledWith(null);
  });

  it("handles network error (non-API, non-abort exception)", async () => {
    const fetchMock = vi.fn<typeof fetch>().mockRejectedValue(
      new TypeError("Failed to fetch"),
    );
    vi.stubGlobal("fetch", fetchMock);

    const setResult = vi.fn();
    const setChatMessages = vi.fn();

    const { result } = renderHook(() =>
      useDecide({
        t: (_ja, en) => en,
        tk: (key) => key,
        query: "test",
        setQuery: vi.fn(),
        setResult,
        setChatMessages,
      }),
    );

    await act(async () => {
      await result.current.runDecision("test query");
    });

    expect(result.current.error).toBe("networkError");
    expect(result.current.executionStatus).toBe("failed");
    expect(setResult).toHaveBeenCalledWith(null);
  });

  it("handles generic non-ok HTTP status (e.g. 422 validation)", async () => {
    const fetchMock = vi.fn<typeof fetch>().mockResolvedValue(
      new Response('{"error":"bad request"}', {
        status: 422,
        headers: { "Content-Type": "application/json" },
      }),
    );
    vi.stubGlobal("fetch", fetchMock);

    const setResult = vi.fn();
    const setChatMessages = vi.fn();

    const { result } = renderHook(() =>
      useDecide({
        t: (_ja, en) => en,
        tk: (key) => key,
        query: "test",
        setQuery: vi.fn(),
        setResult,
        setChatMessages,
      }),
    );

    await act(async () => {
      await result.current.runDecision("test query");
    });

    expect(result.current.error).toBe("validationError");
    expect(result.current.executionStatus).toBe("failed");
  });

  it("notifySseActivity updates latestEvent and executionStatus", () => {
    const { result } = renderHook(() =>
      useDecide({
        t: (_ja, en) => en,
        tk: (key) => key,
        query: "",
        setQuery: vi.fn(),
        setResult: vi.fn(),
        setChatMessages: vi.fn(),
      }),
    );

    act(() => {
      result.current.notifySseActivity("new event");
    });

    expect(result.current.latestEvent).toBe("new event");
  });

  it("successful response sets executionStatus to completed", async () => {
    const payload = buildDecidePayload("req-success", "allow");
    const fetchMock = vi.fn<typeof fetch>().mockResolvedValue(
      new Response(JSON.stringify(payload), {
        status: 200,
        headers: { "Content-Type": "application/json" },
      }),
    );
    vi.stubGlobal("fetch", fetchMock);

    const setResult = vi.fn();
    const setChatMessages = vi.fn();

    const { result } = renderHook(() =>
      useDecide({
        t: (_ja, en) => en,
        tk: (key) => key,
        query: "test",
        setQuery: vi.fn(),
        setResult,
        setChatMessages,
      }),
    );

    await act(async () => {
      await result.current.runDecision("test query");
    });

    expect(result.current.executionStatus).toBe("completed");
    expect(result.current.loading).toBe(false);
    expect(setResult).toHaveBeenCalledWith(payload);
  });

  it("ignores stale completion and only applies latest result", async () => {
    const first = createDeferred<Response>();
    const second = createDeferred<Response>();

    const firstPayload = buildDecidePayload("req-1", "old");
    const secondPayload = buildDecidePayload("req-2", "new");

    const fetchMock = vi
      .fn<typeof fetch>()
      .mockImplementationOnce(() => first.promise)
      .mockImplementationOnce(() => second.promise);

    vi.stubGlobal("fetch", fetchMock);

    const setQuery = vi.fn();
    const setResult = vi.fn();
    const setChatMessages = vi.fn();

    const { result } = renderHook(() =>
      useDecide({
        t: (_ja, en) => en,
        tk: (key) => key,
        query: "q",
        setQuery,
        setResult,
        setChatMessages,
      }),
    );

    await act(async () => {
      void result.current.runDecision("first");
      await Promise.resolve();
      void result.current.runDecision("second");
      second.resolve(
        new Response(JSON.stringify(secondPayload), {
          status: 200,
          headers: { "Content-Type": "application/json" },
        }),
      );
      await Promise.resolve();
      first.resolve(
        new Response(JSON.stringify(firstPayload), {
          status: 200,
          headers: { "Content-Type": "application/json" },
        }),
      );
      await Promise.resolve();
    });

    expect(setResult).toHaveBeenCalledTimes(1);
    expect(setResult).toHaveBeenCalledWith(secondPayload);
  });
});
