#!/usr/bin/env python3
"""Build a deterministic local/offline manifest for reviewer CI artifacts."""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from veritas_os.security.hash import sha256_of_canonical_json  # noqa: E402

MANIFEST_ID = "reviewer-evidence-artifact-manifest-v1"
MANIFEST_VERSION = "v1"
ARTIFACT_NAME = "reviewer-evidence-packet-validation-artifacts"
DEFAULT_OUTPUT_FILENAME = "reviewer-evidence-artifact-manifest.json"
BOUNDARY_NOTE = (
    "local/offline CI reviewer artifact only; no live SaaS/IAM/IdP/SSO/"
    "customer/bank/sanctions/production approval integration"
)
DEFAULT_GENERATED_AT = "1970-01-01T00:00:00Z"
REVIEWER_NOTES = [
    "This manifest describes local/offline Reviewer Evidence Packet CI artifacts.",
    "It records each artifact file role, source, sha256 hash, and size.",
    (
        "It does not connect to live SaaS, IAM, IdP, SSO, customer directories, "
        "banks, sanctions systems, production approval workflows, or live audit stores."
    ),
    (
        "It is not legal advice, regulatory approval, third-party certification, "
        "production audit certification, or proof of live deployment."
    ),
]

REQUIRED_FILE_DEFINITIONS = [
    {
        "path": "reviewer-evidence-packet-validation-report.json",
        "role": "validation_report",
        "source": "generated_by_ci",
        "generated": True,
        "required": True,
        "media_type": "application/json",
        "description": (
            "deterministic validation report generated by the Reviewer Evidence "
            "Packet CI gate"
        ),
    },
    {
        "path": "reviewer-evidence-packet-generated.json",
        "role": "generated_packet",
        "source": "generated_by_ci",
        "generated": True,
        "required": True,
        "media_type": "application/json",
        "description": "current Reviewer Evidence Packet generated from repository code",
    },
    {
        "path": "reviewer-evidence-packet-golden-fixture.json",
        "role": "golden_fixture",
        "source": "checked_in_fixture",
        "generated": False,
        "required": True,
        "media_type": "application/json",
        "description": "checked-in deterministic golden fixture copied into CI artifact",
    },
    {
        "path": "reviewer-evidence-packet-schema.json",
        "role": "json_schema",
        "source": "checked_in_schema",
        "generated": False,
        "required": True,
        "media_type": "application/schema+json",
        "description": (
            "checked-in JSON Schema contract for Reviewer Evidence Packet v1"
        ),
    },
]
OPTIONAL_FILE_DEFINITIONS = [
    {
        "path": "external-reviewer-quickstart.md",
        "role": "quickstart_doc",
        "source": "checked_in_docs",
        "generated": False,
        "required": False,
        "media_type": "text/markdown",
        "description": "checked-in quickstart for external reviewer inspection",
    },
    {
        "path": "external-reviewer-artifact-index.md",
        "role": "artifact_index_doc",
        "source": "checked_in_docs",
        "generated": False,
        "required": False,
        "media_type": "text/markdown",
        "description": "checked-in index of local/offline reviewer artifacts",
    },
]


def _artifact_dir(path: Path | str) -> Path:
    """Return a normalized artifact directory path without resolving symlinks."""
    return Path(path)


def _read_json_object(path: Path) -> dict[str, Any] | None:
    """Return a JSON object from ``path`` when it is available and parseable."""
    if not path.is_file():
        return None
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None
    if not isinstance(payload, dict):
        return None
    return payload


def _deterministic_generated_at(
    artifact_dir: Path,
    generated_at: str | None,
) -> str:
    """Choose a deterministic manifest timestamp from local artifact contents."""
    if generated_at is not None:
        return generated_at
    for relative_path in (
        "reviewer-evidence-packet-validation-report.json",
        "reviewer-evidence-packet-generated.json",
    ):
        payload = _read_json_object(artifact_dir / relative_path)
        if payload is None:
            continue
        candidate = payload.get("generated_at")
        if isinstance(candidate, str) and candidate:
            return candidate
    return DEFAULT_GENERATED_AT


def _sha256_bytes(raw: bytes) -> str:
    """Return the lowercase SHA-256 hex digest for raw bytes."""
    return hashlib.sha256(raw).hexdigest()


def _file_entry(artifact_dir: Path, definition: dict[str, Any]) -> dict[str, Any] | None:
    """Return a manifest file entry for an existing artifact file."""
    relative_path = str(definition["path"])
    file_path = artifact_dir / relative_path
    if not file_path.is_file():
        return None
    raw = file_path.read_bytes()
    entry = copy.deepcopy(definition)
    entry["sha256"] = _sha256_bytes(raw)
    entry["size_bytes"] = len(raw)
    return entry


def compute_reviewer_evidence_artifact_manifest_hash(
    manifest: dict[str, Any],
) -> str:
    """Compute a stable SHA-256 hash for an artifact manifest.

    The ``manifest_hash`` field is excluded so finalizing a manifest cannot
    recursively change the digest it is meant to report.
    """
    payload = copy.deepcopy(manifest)
    payload.pop("manifest_hash", None)
    return sha256_of_canonical_json(payload)


def _aggregate_summary(
    *,
    files: list[dict[str, Any]],
    missing_required_files: list[str],
) -> dict[str, Any]:
    """Return deterministic aggregate manifest counts."""
    return {
        "total_files": len(files),
        "required_files": sum(1 for file_entry in files if file_entry["required"]),
        "optional_files": sum(1 for file_entry in files if not file_entry["required"]),
        "generated_files": sum(1 for file_entry in files if file_entry["generated"]),
        "checked_in_files": sum(
            1 for file_entry in files if not file_entry["generated"]
        ),
        "missing_required_files": list(missing_required_files),
        "total_size_bytes": sum(file_entry["size_bytes"] for file_entry in files),
        "local_offline_only": True,
    }


def build_reviewer_evidence_artifact_manifest(
    *,
    artifact_dir: Path | str,
    generated_at: str | None = None,
) -> dict[str, Any]:
    """Build a deterministic local/offline reviewer artifact manifest.

    Args:
        artifact_dir: Directory containing Reviewer Evidence Packet CI artifacts.
        generated_at: Optional deterministic timestamp override.

    Returns:
        JSON-serializable manifest with file hashes, sizes, summary counts, and
        a deterministic ``manifest_hash``.
    """
    artifact_path = _artifact_dir(artifact_dir)
    files: list[dict[str, Any]] = []
    missing_required_files: list[str] = []

    for definition in REQUIRED_FILE_DEFINITIONS:
        entry = _file_entry(artifact_path, definition)
        if entry is None:
            missing_required_files.append(str(definition["path"]))
            continue
        files.append(entry)

    for definition in OPTIONAL_FILE_DEFINITIONS:
        entry = _file_entry(artifact_path, definition)
        if entry is not None:
            files.append(entry)

    manifest = {
        "manifest_id": MANIFEST_ID,
        "manifest_version": MANIFEST_VERSION,
        "artifact_name": ARTIFACT_NAME,
        "generated_at": _deterministic_generated_at(artifact_path, generated_at),
        "local_offline_only": True,
        "boundary_note": BOUNDARY_NOTE,
        "files": files,
        "aggregate_summary": _aggregate_summary(
            files=files,
            missing_required_files=missing_required_files,
        ),
        "reviewer_notes": list(REVIEWER_NOTES),
        "manifest_hash": "",
    }
    manifest["manifest_hash"] = compute_reviewer_evidence_artifact_manifest_hash(
        manifest
    )
    return manifest


def write_reviewer_evidence_artifact_manifest(
    *,
    artifact_dir: Path | str,
    output_path: Path | str | None = None,
    generated_at: str | None = None,
) -> dict[str, Any]:
    """Build and write the deterministic reviewer artifact manifest.

    Raises:
        FileNotFoundError: If any required artifact file is missing.
    """
    artifact_path = _artifact_dir(artifact_dir)
    destination = (
        Path(output_path)
        if output_path is not None
        else artifact_path / DEFAULT_OUTPUT_FILENAME
    )
    manifest = build_reviewer_evidence_artifact_manifest(
        artifact_dir=artifact_path,
        generated_at=generated_at,
    )
    missing_required_files = manifest["aggregate_summary"]["missing_required_files"]
    if missing_required_files:
        missing = ", ".join(missing_required_files)
        raise FileNotFoundError(f"Missing required artifact files: {missing}")
    destination.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return manifest


def _parse_args(argv: list[str]) -> argparse.Namespace:
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description="Build the Reviewer Evidence Packet artifact manifest."
    )
    parser.add_argument("artifact_dir", help="Reviewer evidence artifact directory")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Write the manifest file and print deterministic JSON to stdout."""
    args = _parse_args(sys.argv[1:] if argv is None else argv)
    try:
        manifest = write_reviewer_evidence_artifact_manifest(
            artifact_dir=args.artifact_dir,
        )
    except (OSError, ValueError) as exc:
        print(str(exc), file=sys.stderr)
        return 1
    print(json.dumps(manifest, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
