import { describe, expect, it } from "vitest";
import {
  isChatRequest,
  isCritiqueItem,
  isDebateView,
  isDecideRequest,
  isDecideResponse,
  isDecisionAlternative,
  isEvidenceItem,
  isEvoTips,
  isFujiDecision,
  isGateOut,
  isHealthResponse,
  isMemoryEraseRequest,
  isMemoryGetRequest,
  isMemoryPutRequest,
  isMemorySearchRequest,
  isPersonaState,
  isStageMetrics,
  isTrustFeedbackRequest,
  isValuesOut,
} from "./index";
import type {
  AutoStop,
  ChatRequest,
  ComplianceConfigBody,
  ComplianceConfigResponse,
  Context,
  CritiqueItem,
  DebateView,
  DecideRequest,
  DecideResponse,
  DeploymentReadinessResponse,
  EvoTips,
  FujiDecision,
  GovernancePolicy,
  GovernancePolicyHistoryResponse,
  GovernancePolicyResponse,
  HealthResponse,
  LogRetention,
  MemoryEraseRequest,
  MemoryGetRequest,
  MemoryGetResponse,
  MemoryKind,
  MemoryPutRequest,
  MemoryPutResponse,
  MemorySearchRequest,
  PersonaState,
  PolicyHistoryEntry,
  ReplayResponse,
  ResponseStyle,
  RetentionClass,
  RiskThresholds,
  StageHealth,
  StageMetrics,
  SystemHaltRequest,
  SystemHaltResponse,
  SystemHaltStatusResponse,
  SystemResumeRequest,
  SystemResumeResponse,
  TimeHorizon,
  TrustFeedbackRequest,
  TrustFeedbackResponse,
  TrustLog,
  TrustVerifyResponse,
} from "./index";

describe("types", () => {
  it("accepts a valid health response shape", () => {
    const response: HealthResponse = {
      ok: true,
      uptime: 120,
      checks: {
        pipeline: "ok",
        memory: "ok",
      },
    };

    expect(response.ok).toBe(true);
  });

  it("validates health response payloads at runtime", () => {
    expect(
      isHealthResponse({
        ok: true,
        uptime: 120,
        checks: {
          pipeline: "ok",
          memory: "ok",
        },
      })
    ).toBe(true);

    expect(
      isHealthResponse({
        ok: true,
        uptime: "not-a-number",
        checks: {
          pipeline: "ok",
          memory: "ok",
        },
      })
    ).toBe(false);

    expect(
      isHealthResponse({
        ok: true,
        uptime: 120,
        checks: {
          pipeline: "ok",
        },
      })
    ).toBe(false);
  });

  it("accepts a backend-aligned decide response shape", () => {
    const response: DecideResponse = {
      ok: true,
      error: null,
      request_id: "req_123",
      version: "veritas-api 1.x",
      chosen: { id: "alt-1" },
      alternatives: [
        {
          id: "alt-1",
          title: "Option A",
          description: "A description",
          score: 0.9
        }
      ],
      options: [
        {
          id: "alt-1",
          title: "Option A",
          description: "A description",
          score: 0.9
        }
      ],
      decision_status: "allow",
      rejection_reason: null,
      values: {
        scores: { safety: 0.9 },
        total: 0.9,
        top_factors: ["safety"],
        rationale: "safe"
      },
      telos_score: 0.8,
      fuji: { status: "allow" },
      gate: {
        risk: 0.1,
        telos_score: 0.8,
        decision_status: "allow",
        modifications: []
      },
      evidence: [
        {
          source: "memory",
          snippet: "evidence",
          confidence: 0.7
        }
      ],
      critique: [],
      debate: [],
      extras: {},
      reason: null,
      rsi_note: null,
      evo: null,
      meta: {},
      plan: null,
      planner: null,
      persona: {},
      memory_citations: [],
      memory_used_count: 0,
      trust_log: null,
      ai_disclosure: "This content was generated by an AI system.",
      regulation_notice: "EU AI Act Art. 50 compliance notice."
    };

    expect(response.decision_status).toBe("allow");
  });

  it("validates decide response payloads at runtime", () => {
    const validPayload: DecideResponse = {
      ok: true,
      error: null,
      request_id: "req_123",
      version: "veritas-api 1.x",
      chosen: { id: "alt-1" },
      alternatives: [],
      options: [],
      decision_status: "allow",
      rejection_reason: null,
      values: null,
      telos_score: 0.8,
      fuji: {},
      gate: {
        risk: 0.1,
        telos_score: 0.8,
        decision_status: "allow",
        modifications: []
      },
      evidence: [],
      critique: [],
      debate: [],
      extras: {},
      reason: null,
      rsi_note: null,
      evo: null,
      meta: {},
      plan: null,
      planner: null,
      persona: {},
      memory_citations: [],
      memory_used_count: 0,
      trust_log: null,
      ai_disclosure: "This content was generated by an AI system.",
      regulation_notice: "EU AI Act Art. 50 compliance notice."
    };

    expect(isDecideResponse(validPayload)).toBe(true);

    expect(
      isDecideResponse({
        ...validPayload,
        decision_status: "unknown"
      })
    ).toBe(false);
  });

  it("TrustLog type includes sha256 field for hash-chain verification", () => {
    const log: TrustLog = {
      request_id: "req-1",
      created_at: "2026-02-12T00:00:00Z",
      sources: ["memory"],
      critics: [],
      checks: ["fuji"],
      approver: "system",
      sha256: "a".repeat(64),
      sha256_prev: "b".repeat(64),
    };

    expect(log.sha256).toBe("a".repeat(64));
    expect(log.sha256_prev).toBe("b".repeat(64));
  });

  it("CritiqueItem type matches backend CritiqueItem schema", () => {
    const item: CritiqueItem = {
      issue: "Potential bias detected",
      severity: "high",
      fix: "Add diverse training data",
    };

    expect(item.severity).toBe("high");
    expect(item.fix).toBe("Add diverse training data");
  });

  it("DebateView type matches backend DebateView schema", () => {
    const view: DebateView = {
      stance: "for",
      argument: "This approach maximizes safety",
      score: 0.85,
    };

    expect(view.score).toBe(0.85);
  });

  it("FujiDecision type matches backend FujiDecision schema", () => {
    const decision: FujiDecision = {
      status: "allow",
      reasons: ["safe content"],
      violations: [],
    };

    expect(decision.status).toBe("allow");
    expect(decision.violations).toHaveLength(0);
  });

  it("MemoryKind type matches backend VALID_MEMORY_KINDS", () => {
    const kinds: MemoryKind[] = ["semantic", "episodic", "skills", "doc", "plan"];
    expect(kinds).toHaveLength(5);
    expect(kinds).toContain("semantic");
    expect(kinds).toContain("plan");
  });

  it("TimeHorizon type matches backend Context.time_horizon", () => {
    const horizons: TimeHorizon[] = ["short", "mid", "long"];
    expect(horizons).toHaveLength(3);
  });

  it("ResponseStyle type matches backend Context.response_style", () => {
    const styles: ResponseStyle[] = ["logic", "emotional", "business", "expert", "casual"];
    expect(styles).toHaveLength(5);
  });

  it("RetentionClass type matches backend ALLOWED_RETENTION_CLASSES", () => {
    const classes: RetentionClass[] = ["short", "standard", "long", "regulated"];
    expect(classes).toHaveLength(4);
  });

  it("PersonaState type matches backend PersonaState schema", () => {
    const state: PersonaState = {
      name: "VERITAS",
      style: "direct, strategic, honest",
      tone: "warm",
      principles: ["honesty", "dignity", "growth"],
      last_updated: "2026-03-10T00:00:00Z",
    };

    expect(state.name).toBe("VERITAS");
    expect(state.principles).toHaveLength(3);
  });

  it("validates PersonaState payloads at runtime", () => {
    expect(
      isPersonaState({
        name: "VERITAS",
        style: "direct",
        tone: "warm",
        principles: ["honesty"],
      })
    ).toBe(true);

    expect(
      isPersonaState({
        name: "VERITAS",
        style: "direct",
        tone: "warm",
        principles: ["honesty"],
        last_updated: null,
      })
    ).toBe(true);

    expect(isPersonaState(null)).toBe(false);
    expect(isPersonaState({ name: "VERITAS" })).toBe(false);
    expect(
      isPersonaState({
        name: "VERITAS",
        style: "direct",
        tone: "warm",
        principles: [123],
      })
    ).toBe(false);
  });

  it("EvoTips type matches backend EvoTips schema", () => {
    const tips: EvoTips = {
      insights: { safety: "high" },
      actions: ["review policy"],
      next_prompts: ["consider edge cases"],
      notes: ["note 1"],
    };

    expect(tips.actions).toHaveLength(1);
    expect(tips.next_prompts).toHaveLength(1);
  });

  it("validates EvoTips payloads at runtime", () => {
    expect(
      isEvoTips({
        insights: {},
        actions: [],
        next_prompts: [],
        notes: [],
      })
    ).toBe(true);

    expect(isEvoTips(null)).toBe(false);
    expect(isEvoTips({ insights: {} })).toBe(false);
    expect(
      isEvoTips({
        insights: {},
        actions: [123],
        next_prompts: [],
        notes: [],
      })
    ).toBe(false);
  });

  it("ChatRequest type matches backend ChatRequest schema", () => {
    const req: ChatRequest = {
      message: "Hello, VERITAS",
      session_id: "sess_abc",
      memory_auto_put: true,
      persona_evolve: true,
    };

    expect(req.message).toBe("Hello, VERITAS");
  });

  it("ChatRequest accepts minimal required fields", () => {
    const req: ChatRequest = {
      message: "Hello",
    };

    expect(req.message).toBe("Hello");
    expect(req.session_id).toBeUndefined();
  });

  it("GovernancePolicy type matches backend governance.py GovernancePolicy", () => {
    const policy: GovernancePolicy = {
      version: "governance_v1",
      fuji_rules: {
        pii_check: true,
        self_harm_block: true,
        illicit_block: true,
        violence_review: true,
        minors_review: true,
        keyword_hard_block: true,
        keyword_soft_flag: true,
        llm_safety_head: true,
      },
      risk_thresholds: {
        allow_upper: 0.4,
        warn_upper: 0.65,
        human_review_upper: 0.85,
        deny_upper: 1.0,
      },
      auto_stop: {
        enabled: true,
        max_risk_score: 0.85,
        max_consecutive_rejects: 5,
        max_requests_per_minute: 60,
      },
      log_retention: {
        retention_days: 90,
        audit_level: "full",
        include_fields: ["status", "risk", "reasons", "violations", "categories"],
        redact_before_log: true,
        max_log_size: 10000,
      },
      updated_at: "2026-03-10T00:00:00Z",
      updated_by: "system",
    };

    expect(policy.version).toBe("governance_v1");
    expect(policy.fuji_rules.pii_check).toBe(true);
    expect(policy.risk_thresholds.allow_upper).toBe(0.4);
    expect(policy.auto_stop.max_consecutive_rejects).toBe(5);
    expect(policy.log_retention.retention_days).toBe(90);
  });

  it("GovernancePolicyResponse wraps GovernancePolicy with ok flag", () => {
    const response: GovernancePolicyResponse = {
      ok: true,
      policy: {
        version: "governance_v1",
        fuji_rules: {
          pii_check: true,
          self_harm_block: true,
          illicit_block: true,
          violence_review: true,
          minors_review: true,
          keyword_hard_block: true,
          keyword_soft_flag: true,
          llm_safety_head: true,
        },
        risk_thresholds: {
          allow_upper: 0.4,
          warn_upper: 0.65,
          human_review_upper: 0.85,
          deny_upper: 1.0,
        },
        auto_stop: {
          enabled: true,
          max_risk_score: 0.85,
          max_consecutive_rejects: 5,
          max_requests_per_minute: 60,
        },
        log_retention: {
          retention_days: 90,
          audit_level: "full",
          include_fields: ["status", "risk"],
          redact_before_log: true,
          max_log_size: 10000,
        },
        updated_at: "2026-03-10T00:00:00Z",
        updated_by: "system",
      },
    };

    expect(response.ok).toBe(true);
    expect(response.policy.version).toBe("governance_v1");
  });

  it("RiskThresholds type matches backend RiskThresholds fields", () => {
    const thresholds: RiskThresholds = {
      allow_upper: 0.4,
      warn_upper: 0.65,
      human_review_upper: 0.85,
      deny_upper: 1.0,
    };

    expect(thresholds.allow_upper).toBeLessThan(thresholds.warn_upper);
    expect(thresholds.warn_upper).toBeLessThan(thresholds.human_review_upper);
    expect(thresholds.human_review_upper).toBeLessThanOrEqual(thresholds.deny_upper);
  });

  it("AutoStop type matches backend AutoStop constraints", () => {
    const autoStop: AutoStop = {
      enabled: true,
      max_risk_score: 0.85,
      max_consecutive_rejects: 5,
      max_requests_per_minute: 60,
    };

    expect(autoStop.enabled).toBe(true);
    expect(autoStop.max_risk_score).toBeLessThanOrEqual(1.0);
  });

  it("LogRetention type matches backend LogRetention fields", () => {
    const retention: LogRetention = {
      retention_days: 90,
      audit_level: "full",
      include_fields: ["status", "risk", "reasons", "violations", "categories"],
      redact_before_log: true,
      max_log_size: 10000,
    };

    expect(retention.include_fields).toContain("status");
    expect(retention.retention_days).toBe(90);
  });

  it("isDecideResponse accepts payload with undefined plan/planner (consistent with evo/rsi_note)", () => {
    const base = {
      ok: true,
      error: null,
      request_id: "req_123",
      version: "veritas-api 1.x",
      chosen: {},
      alternatives: [],
      options: [],
      decision_status: "allow",
      rejection_reason: null,
      values: null,
      telos_score: 0.8,
      fuji: {},
      gate: {
        risk: 0.1,
        telos_score: 0.8,
        decision_status: "allow",
        modifications: [],
      },
      evidence: [],
      critique: [],
      debate: [],
      extras: {},
      meta: {},
      persona: {},
      memory_citations: [],
      memory_used_count: 0,
      trust_log: null,
      ai_disclosure: "disclosure",
      regulation_notice: "notice",
    };

    // plan and planner undefined (omitted from payload)
    expect(isDecideResponse({ ...base })).toBe(true);

    // plan and planner explicitly null
    expect(isDecideResponse({ ...base, plan: null, planner: null })).toBe(true);

    // evo and rsi_note undefined (should also work)
    expect(isDecideResponse({ ...base, evo: undefined, rsi_note: undefined })).toBe(true);
  });

  it("isDecideResponse accepts payload with optional nullable fields (affected_parties_notice, query, pipeline_steps, deterministic_replay)", () => {
    const base = {
      ok: true,
      error: null,
      request_id: "req_123",
      version: "veritas-api 1.x",
      chosen: {},
      alternatives: [],
      options: [],
      decision_status: "allow",
      rejection_reason: null,
      values: null,
      telos_score: 0.8,
      fuji: {},
      gate: {
        risk: 0.1,
        telos_score: 0.8,
        decision_status: "allow",
        modifications: [],
      },
      evidence: [],
      critique: [],
      debate: [],
      extras: {},
      meta: {},
      persona: {},
      memory_citations: [],
      memory_used_count: 0,
      trust_log: null,
      ai_disclosure: "disclosure",
      regulation_notice: "notice",
    };

    // omitted (undefined)
    expect(isDecideResponse({ ...base })).toBe(true);

    // explicitly null
    expect(isDecideResponse({
      ...base,
      affected_parties_notice: null,
      query: null,
      pipeline_steps: null,
      deterministic_replay: null,
    })).toBe(true);

    // with values
    expect(isDecideResponse({
      ...base,
      affected_parties_notice: { parties: ["user-1"] },
      query: "test query",
      pipeline_steps: ["step1", "step2"],
      deterministic_replay: { seed: 42 },
    })).toBe(true);
  });

  it("isDecideResponse rejects invalid affected_parties_notice type", () => {
    const base = {
      ok: true,
      error: null,
      request_id: "req_123",
      version: "veritas-api 1.x",
      chosen: {},
      alternatives: [],
      options: [],
      decision_status: "allow",
      rejection_reason: null,
      values: null,
      telos_score: 0.8,
      fuji: {},
      gate: {
        risk: 0.1,
        telos_score: 0.8,
        decision_status: "allow",
        modifications: [],
      },
      evidence: [],
      critique: [],
      debate: [],
      extras: {},
      meta: {},
      persona: {},
      memory_citations: [],
      memory_used_count: 0,
      trust_log: null,
      ai_disclosure: "disclosure",
      regulation_notice: "notice",
    };

    // affected_parties_notice must be null, undefined, or object
    expect(isDecideResponse({ ...base, affected_parties_notice: "invalid" })).toBe(false);

    // query must be null, undefined, or string
    expect(isDecideResponse({ ...base, query: 123 })).toBe(false);

    // pipeline_steps must be null, undefined, or array
    expect(isDecideResponse({ ...base, pipeline_steps: "not-an-array" })).toBe(false);

    // deterministic_replay must be null, undefined, or object
    expect(isDecideResponse({ ...base, deterministic_replay: "invalid" })).toBe(false);
  });

  it("DecideResponse critique and debate use typed arrays (CritiqueItem[] and DebateView[])", () => {
    const response: DecideResponse = {
      ok: true,
      error: null,
      request_id: "req_123",
      version: "veritas-api 1.x",
      chosen: {},
      alternatives: [],
      options: [],
      decision_status: "allow",
      rejection_reason: null,
      values: null,
      telos_score: 0.8,
      fuji: {},
      gate: {
        risk: 0.1,
        telos_score: 0.8,
        decision_status: "allow",
        modifications: [],
      },
      evidence: [],
      critique: [{ issue: "bias detected", severity: "high", fix: "add diversity" }],
      debate: [{ stance: "for", argument: "safe approach", score: 0.9 }],
      extras: {},
      reason: null,
      rsi_note: null,
      evo: null,
      meta: {},
      plan: null,
      planner: null,
      persona: {},
      memory_citations: [],
      memory_used_count: 0,
      trust_log: null,
      ai_disclosure: "AI generated",
      regulation_notice: "EU AI Act",
    };

    // critique items are typed — access CritiqueItem fields
    expect(response.critique[0].issue).toBe("bias detected");
    expect(response.critique[0].severity).toBe("high");
    expect(response.critique[0].fix).toBe("add diversity");

    // debate items are typed — access DebateView fields
    expect(response.debate[0].stance).toBe("for");
    expect(response.debate[0].argument).toBe("safe approach");
    expect(response.debate[0].score).toBe(0.9);
  });

  it("validates CritiqueItem payloads at runtime", () => {
    expect(
      isCritiqueItem({
        issue: "Potential bias",
        severity: "high",
        fix: "Add diverse data",
      })
    ).toBe(true);

    expect(
      isCritiqueItem({
        issue: "Minor issue",
        severity: "low",
      })
    ).toBe(true);

    expect(
      isCritiqueItem({
        issue: "Moderate issue",
        severity: "med",
      })
    ).toBe(true);

    expect(
      isCritiqueItem({
        issue: "Issue",
        severity: "high",
        fix: null,
      })
    ).toBe(true);

    expect(isCritiqueItem(null)).toBe(false);
    expect(isCritiqueItem({ issue: "x" })).toBe(false);
    expect(
      isCritiqueItem({ issue: "x", severity: "critical" })
    ).toBe(false);
    expect(
      isCritiqueItem({ issue: 123, severity: "low" })
    ).toBe(false);
    expect(
      isCritiqueItem({ issue: "x", severity: "high", fix: 42 })
    ).toBe(false);
  });

  it("validates DebateView payloads at runtime", () => {
    expect(
      isDebateView({
        stance: "for",
        argument: "This approach maximizes safety",
        score: 0.85,
      })
    ).toBe(true);

    expect(isDebateView(null)).toBe(false);
    expect(isDebateView({ stance: "for" })).toBe(false);
    expect(
      isDebateView({ stance: "for", argument: "test", score: "not-a-number" })
    ).toBe(false);
    expect(
      isDebateView({ stance: 123, argument: "test", score: 0.5 })
    ).toBe(false);
  });

  it("validates EvidenceItem payloads at runtime", () => {
    expect(
      isEvidenceItem({
        source: "memory",
        snippet: "evidence text",
        confidence: 0.9,
      })
    ).toBe(true);

    expect(
      isEvidenceItem({
        source: "web",
        uri: "https://example.com",
        title: "Example",
        snippet: "text",
        confidence: 0.7,
      })
    ).toBe(true);

    expect(
      isEvidenceItem({
        source: "unknown",
        snippet: "",
        confidence: 0.7,
        uri: null,
        title: null,
      })
    ).toBe(true);

    expect(isEvidenceItem(null)).toBe(false);
    expect(isEvidenceItem({ source: "x" })).toBe(false);
    expect(
      isEvidenceItem({ source: "x", snippet: "y", confidence: "high" })
    ).toBe(false);
    expect(
      isEvidenceItem({ source: "x", snippet: "y", confidence: 0.5, uri: 123 })
    ).toBe(false);
  });

  it("validates FujiDecision payloads at runtime", () => {
    expect(
      isFujiDecision({
        status: "allow",
        reasons: ["safe content"],
        violations: [],
      })
    ).toBe(true);

    expect(
      isFujiDecision({
        status: "block",
        reasons: [],
        violations: ["harmful content"],
      })
    ).toBe(true);

    expect(isFujiDecision(null)).toBe(false);
    expect(isFujiDecision({ status: "allow" })).toBe(false);
    expect(
      isFujiDecision({ status: "unknown", reasons: [], violations: [] })
    ).toBe(false);
    expect(
      isFujiDecision({ status: "allow", reasons: [123], violations: [] })
    ).toBe(false);
    expect(
      isFujiDecision({ status: "allow", reasons: [], violations: [456] })
    ).toBe(false);
  });

  it("validates DecisionAlternative payloads at runtime", () => {
    expect(
      isDecisionAlternative({
        id: "alt-1",
        title: "Option A",
        description: "Description of A",
        score: 0.9,
      })
    ).toBe(true);

    expect(
      isDecisionAlternative({
        id: "alt-2",
        title: "Option B",
        description: "Description of B",
        score: 0.8,
        score_raw: 0.75,
        world: { economy: "good" },
        meta: { source: "pipeline" },
      })
    ).toBe(true);

    expect(
      isDecisionAlternative({
        id: "alt-3",
        title: "Option C",
        description: "Description of C",
        score: 0.7,
        score_raw: null,
        world: null,
        meta: null,
      })
    ).toBe(true);

    expect(isDecisionAlternative(null)).toBe(false);
    expect(isDecisionAlternative({ id: "x" })).toBe(false);
    expect(
      isDecisionAlternative({
        id: "x",
        title: "t",
        description: "d",
        score: "not-a-number",
      })
    ).toBe(false);
    expect(
      isDecisionAlternative({
        id: "x",
        title: "t",
        description: "d",
        score: 1,
        score_raw: "invalid",
      })
    ).toBe(false);
    expect(
      isDecisionAlternative({
        id: "x",
        title: "t",
        description: "d",
        score: 1,
        world: "not-an-object",
      })
    ).toBe(false);
  });

  it("validates GateOut payloads at runtime", () => {
    expect(
      isGateOut({
        risk: 0.1,
        telos_score: 0.8,
        decision_status: "allow",
        modifications: [],
      })
    ).toBe(true);

    expect(
      isGateOut({
        risk: 0.9,
        telos_score: 0.3,
        bias: 0.2,
        decision_status: "block",
        reason: "too risky",
        modifications: ["reduce scope"],
      })
    ).toBe(true);

    expect(
      isGateOut({
        risk: 0.5,
        telos_score: 0.5,
        decision_status: "modify",
        modifications: ["adjust scope", { field: "budget", action: "reduce" }],
      })
    ).toBe(true);

    expect(
      isGateOut({
        risk: 0.5,
        telos_score: 0.5,
        bias: null,
        decision_status: "modify",
        reason: null,
        modifications: [],
      })
    ).toBe(true);

    expect(isGateOut(null)).toBe(false);
    expect(isGateOut({ risk: 0.1 })).toBe(false);
    expect(
      isGateOut({
        risk: 0.1,
        telos_score: 0.5,
        decision_status: "invalid",
        modifications: [],
      })
    ).toBe(false);
    expect(
      isGateOut({
        risk: 0.1,
        telos_score: 0.5,
        decision_status: "allow",
        modifications: [],
        bias: "not-a-number",
      })
    ).toBe(false);
    expect(
      isGateOut({
        risk: 0.1,
        telos_score: 0.5,
        decision_status: "allow",
        modifications: [null],
      })
    ).toBe(false);
  });

  it("validates ValuesOut payloads at runtime", () => {
    expect(
      isValuesOut({
        scores: { safety: 0.9, fairness: 0.8 },
        total: 0.85,
        top_factors: ["safety", "fairness"],
        rationale: "Safe and fair",
      })
    ).toBe(true);

    expect(
      isValuesOut({
        scores: { safety: 0.9 },
        total: 0.9,
        top_factors: ["safety"],
        rationale: "safe",
        ema: 0.88,
      })
    ).toBe(true);

    expect(
      isValuesOut({
        scores: {},
        total: 0,
        top_factors: [],
        rationale: "",
        ema: null,
      })
    ).toBe(true);

    expect(isValuesOut(null)).toBe(false);
    expect(isValuesOut({ scores: {} })).toBe(false);
    expect(
      isValuesOut({
        scores: "not-object",
        total: 0,
        top_factors: [],
        rationale: "",
      })
    ).toBe(false);
    expect(
      isValuesOut({
        scores: {},
        total: 0,
        top_factors: [123],
        rationale: "",
      })
    ).toBe(false);
    expect(
      isValuesOut({
        scores: {},
        total: 0,
        top_factors: [],
        rationale: "",
        ema: "not-a-number",
      })
    ).toBe(false);
  });

  it("validates ChatRequest payloads at runtime", () => {
    expect(
      isChatRequest({
        message: "Hello, VERITAS",
      })
    ).toBe(true);

    expect(
      isChatRequest({
        message: "Hello",
        session_id: "sess_abc",
        memory_auto_put: true,
        persona_evolve: false,
      })
    ).toBe(true);

    expect(
      isChatRequest({
        message: "Hello",
        session_id: null,
      })
    ).toBe(true);

    expect(isChatRequest(null)).toBe(false);
    expect(isChatRequest({})).toBe(false);
    expect(isChatRequest({ message: 123 })).toBe(false);
    expect(
      isChatRequest({ message: "Hello", session_id: 456 })
    ).toBe(false);
    expect(
      isChatRequest({ message: "Hello", memory_auto_put: "yes" })
    ).toBe(false);
    expect(
      isChatRequest({ message: "Hello", persona_evolve: "yes" })
    ).toBe(false);
  });

  it("validates TrustFeedbackRequest payloads at runtime", () => {
    expect(isTrustFeedbackRequest({})).toBe(true);
    expect(
      isTrustFeedbackRequest({
        user_id: "u1",
        score: 0.8,
        note: "good",
        source: "manual",
      })
    ).toBe(true);
    expect(isTrustFeedbackRequest({ user_id: null })).toBe(true);
    expect(isTrustFeedbackRequest({ score: 0.5 })).toBe(true);

    expect(isTrustFeedbackRequest(null)).toBe(false);
    expect(isTrustFeedbackRequest({ score: "high" })).toBe(false);
    expect(isTrustFeedbackRequest({ note: 123 })).toBe(false);
    expect(isTrustFeedbackRequest({ source: 456 })).toBe(false);
    expect(isTrustFeedbackRequest({ user_id: 789 })).toBe(false);
  });

  it("validates DecideRequest payloads at runtime", () => {
    expect(isDecideRequest({})).toBe(true);
    expect(
      isDecideRequest({
        query: "What should I do?",
        context: { user_id: "u1", query: "test" },
        alternatives: [{ title: "A" }],
        min_evidence: 2,
        memory_auto_put: true,
        persona_evolve: false,
      })
    ).toBe(true);

    expect(isDecideRequest(null)).toBe(false);
    expect(isDecideRequest({ query: 123 })).toBe(false);
    expect(isDecideRequest({ context: "bad" })).toBe(false);
    expect(isDecideRequest({ alternatives: "bad" })).toBe(false);
    expect(isDecideRequest({ min_evidence: "bad" })).toBe(false);
    expect(isDecideRequest({ memory_auto_put: "yes" })).toBe(false);
    expect(isDecideRequest({ persona_evolve: "yes" })).toBe(false);
  });

  it("validates MemoryPutRequest payloads at runtime", () => {
    expect(isMemoryPutRequest({})).toBe(true);
    expect(
      isMemoryPutRequest({
        user_id: "u1",
        key: "k1",
        text: "hello",
        tags: ["tag1"],
        kind: "semantic",
        retention_class: "standard",
        meta: {},
        expires_at: 1234567890,
        legal_hold: false,
      })
    ).toBe(true);
    expect(isMemoryPutRequest({ user_id: null, key: null })).toBe(true);
    expect(isMemoryPutRequest({ retention_class: null })).toBe(true);
    expect(isMemoryPutRequest({ expires_at: null })).toBe(true);

    expect(isMemoryPutRequest(null)).toBe(false);
    expect(isMemoryPutRequest({ text: 123 })).toBe(false);
    expect(isMemoryPutRequest({ tags: [123] })).toBe(false);
    expect(isMemoryPutRequest({ kind: 123 })).toBe(false);
    expect(isMemoryPutRequest({ meta: "bad" })).toBe(false);
    expect(isMemoryPutRequest({ expires_at: "bad" })).toBe(false);
    expect(isMemoryPutRequest({ legal_hold: "bad" })).toBe(false);
  });

  it("validates MemoryGetRequest payloads at runtime", () => {
    expect(isMemoryGetRequest({ key: "k1" })).toBe(true);
    expect(isMemoryGetRequest({ user_id: "u1", key: "k1" })).toBe(true);
    expect(isMemoryGetRequest({ user_id: null, key: "k1" })).toBe(true);

    expect(isMemoryGetRequest(null)).toBe(false);
    expect(isMemoryGetRequest({})).toBe(false);
    expect(isMemoryGetRequest({ key: 123 })).toBe(false);
    expect(isMemoryGetRequest({ user_id: 123, key: "k1" })).toBe(false);
  });

  it("validates MemorySearchRequest payloads at runtime", () => {
    expect(isMemorySearchRequest({})).toBe(true);
    expect(
      isMemorySearchRequest({
        user_id: "u1",
        query: "test",
        k: 10,
        min_sim: 0.5,
        kinds: ["semantic", "doc"],
      })
    ).toBe(true);
    expect(isMemorySearchRequest({ kinds: "semantic" })).toBe(true);
    expect(isMemorySearchRequest({ kinds: null })).toBe(true);

    expect(isMemorySearchRequest(null)).toBe(false);
    expect(isMemorySearchRequest({ query: 123 })).toBe(false);
    expect(isMemorySearchRequest({ k: "bad" })).toBe(false);
    expect(isMemorySearchRequest({ min_sim: "bad" })).toBe(false);
    expect(isMemorySearchRequest({ kinds: 123 })).toBe(false);
    expect(isMemorySearchRequest({ kinds: [123] })).toBe(false);
  });

  it("validates MemoryEraseRequest payloads at runtime", () => {
    expect(isMemoryEraseRequest({})).toBe(true);
    expect(
      isMemoryEraseRequest({
        user_id: "u1",
        reason: "user_request",
        actor: "api",
      })
    ).toBe(true);
    expect(isMemoryEraseRequest({ user_id: null })).toBe(true);

    expect(isMemoryEraseRequest(null)).toBe(false);
    expect(isMemoryEraseRequest({ reason: 123 })).toBe(false);
    expect(isMemoryEraseRequest({ actor: 123 })).toBe(false);
    expect(isMemoryEraseRequest({ user_id: 123 })).toBe(false);
  });

  it("assigns new type interfaces correctly", () => {
    const trustFeedback: TrustFeedbackRequest = { score: 0.8, note: "good" };
    expect(trustFeedback.score).toBe(0.8);

    const decideReq: DecideRequest = { query: "test" };
    expect(decideReq.query).toBe("test");

    const memPut: MemoryPutRequest = { text: "hello", kind: "semantic" };
    expect(memPut.kind).toBe("semantic");

    const memGet: MemoryGetRequest = { key: "k1" };
    expect(memGet.key).toBe("k1");

    const memSearch: MemorySearchRequest = { query: "test", k: 5 };
    expect(memSearch.k).toBe(5);

    const memErase: MemoryEraseRequest = { reason: "gdpr" };
    expect(memErase.reason).toBe("gdpr");
  });

  it("validates StageMetrics payloads at runtime", () => {
    expect(isStageMetrics({ health: "ok" })).toBe(true);
    expect(isStageMetrics({ health: "warning", latency_ms: 42.5 })).toBe(true);
    expect(isStageMetrics({ health: "failed", latency_ms: null, summary: "timeout", detail: "stage timed out", reason: "slow network" })).toBe(true);
    expect(isStageMetrics({ health: "unknown" })).toBe(true);
    expect(isStageMetrics({ health: "ok", extra_field: 123 })).toBe(true);

    expect(isStageMetrics(null)).toBe(false);
    expect(isStageMetrics({})).toBe(false);
    expect(isStageMetrics({ health: "invalid" })).toBe(false);
    expect(isStageMetrics({ health: 123 })).toBe(false);
    expect(isStageMetrics({ health: "ok", latency_ms: "not-a-number" })).toBe(false);
    expect(isStageMetrics({ health: "ok", summary: 42 })).toBe(false);
    expect(isStageMetrics({ health: "ok", detail: true })).toBe(false);
    expect(isStageMetrics({ health: "ok", reason: 99 })).toBe(false);
  });

  it("assigns StageMetrics interface correctly", () => {
    const metrics: StageMetrics = {
      health: "ok",
      latency_ms: 12.5,
      summary: "Evidence gathered",
      detail: "Fetched 3 sources",
      reason: null,
    };
    expect(metrics.health).toBe("ok");
    expect(metrics.latency_ms).toBe(12.5);
  });

  it("assigns StageHealth type correctly", () => {
    const statuses: StageHealth[] = ["ok", "warning", "failed", "unknown"];
    expect(statuses).toHaveLength(4);
  });

  it("assigns response type interfaces correctly", () => {
    const memPutResp: MemoryPutResponse = {
      ok: true,
      legacy: { saved: true, key: "k1" },
      vector: { saved: true, id: "v1", kind: "semantic", tags: ["a"] },
      size: 128,
      lifecycle: { retention_class: "standard", expires_at: null, legal_hold: false },
    };
    expect(memPutResp.ok).toBe(true);
    expect(memPutResp.legacy.saved).toBe(true);
    expect(memPutResp.vector.kind).toBe("semantic");
    expect(memPutResp.lifecycle.legal_hold).toBe(false);

    const memGetResp: MemoryGetResponse = { ok: true, value: { data: 42 } };
    expect(memGetResp.ok).toBe(true);

    const replayResp: ReplayResponse = {
      ok: true,
      decision_id: "d1",
      replay_path: "/path",
      match: true,
      diff_summary: "no diff",
      replay_time_ms: 100,
    };
    expect(replayResp.match).toBe(true);

    const feedbackResp: TrustFeedbackResponse = { ok: true };
    expect(feedbackResp.ok).toBe(true);

    const verifyResp: TrustVerifyResponse = { ok: true, valid: true, detail: "chain intact" };
    expect(verifyResp.valid).toBe(true);

    const complianceResp: ComplianceConfigResponse = { ok: true, config: { eu_ai_act_mode: true } };
    expect(complianceResp.config.eu_ai_act_mode).toBe(true);

    const readinessResp: DeploymentReadinessResponse = { ok: true, ready: false, checks: { safety: "pass" } };
    expect(readinessResp.ready).toBe(false);

    const haltResp: SystemHaltResponse = { ok: true, halted: true };
    expect(haltResp.halted).toBe(true);

    const resumeResp: SystemResumeResponse = { ok: true, halted: false };
    expect(resumeResp.halted).toBe(false);

    const statusResp: SystemHaltStatusResponse = { ok: true, halted: false, reason: null };
    expect(statusResp.reason).toBeNull();

    const historyEntry: PolicyHistoryEntry = {
      timestamp: "2025-01-01T00:00:00Z",
      actor: "admin",
      previous: {},
      new: {},
    };
    expect(historyEntry.actor).toBe("admin");

    const historyResp: GovernancePolicyHistoryResponse = { ok: true, history: [historyEntry] };
    expect(historyResp.history).toHaveLength(1);
  });

  it("assigns request type interfaces correctly", () => {
    const complianceBody: ComplianceConfigBody = { eu_ai_act_mode: true, safety_threshold: 0.9 };
    expect(complianceBody.eu_ai_act_mode).toBe(true);

    const haltReq: SystemHaltRequest = { reason: "emergency", operator: "admin1" };
    expect(haltReq.reason).toBe("emergency");
    expect(haltReq.operator).toBe("admin1");

    const resumeReq: SystemResumeRequest = { operator: "admin1", comment: "issue resolved" };
    expect(resumeReq.operator).toBe("admin1");
    expect(resumeReq.comment).toBe("issue resolved");

    const resumeReqMinimal: SystemResumeRequest = { operator: "admin2" };
    expect(resumeReqMinimal.operator).toBe("admin2");
  });

  it("DecideResponse.persona accepts typed PersonaState (OpenAPI $ref alignment)", () => {
    const persona: PersonaState = {
      name: "VERITAS",
      style: "direct, strategic, honest",
      tone: "warm",
      principles: ["honesty", "dignity", "growth"],
      last_updated: "2026-03-10T00:00:00Z",
    };
    const response: DecideResponse = {
      ok: true,
      error: null,
      request_id: "req_typed_persona",
      version: "veritas-api 1.x",
      chosen: {},
      alternatives: [],
      options: [],
      decision_status: "allow",
      rejection_reason: null,
      values: null,
      telos_score: 0.8,
      fuji: {},
      gate: { risk: 0.1, telos_score: 0.8, decision_status: "allow", modifications: [] },
      evidence: [],
      critique: [],
      debate: [],
      extras: {},
      reason: null,
      rsi_note: null,
      evo: null,
      meta: {},
      plan: null,
      planner: null,
      persona,
      memory_citations: [],
      memory_used_count: 0,
      trust_log: null,
      ai_disclosure: "disclosure",
      regulation_notice: "notice",
    };

    expect(isDecideResponse(response)).toBe(true);
    expect(isPersonaState(response.persona)).toBe(true);
  });

  it("DecideResponse.evo accepts typed EvoTips (OpenAPI $ref alignment)", () => {
    const evo: EvoTips = {
      insights: { key: "value" },
      actions: ["action1"],
      next_prompts: ["prompt1"],
      notes: ["note1"],
    };
    const response: DecideResponse = {
      ok: true,
      error: null,
      request_id: "req_typed_evo",
      version: "veritas-api 1.x",
      chosen: {},
      alternatives: [],
      options: [],
      decision_status: "allow",
      rejection_reason: null,
      values: null,
      telos_score: 0.8,
      fuji: {},
      gate: { risk: 0.1, telos_score: 0.8, decision_status: "allow", modifications: [] },
      evidence: [],
      critique: [],
      debate: [],
      extras: {},
      reason: null,
      rsi_note: null,
      evo,
      meta: {},
      plan: null,
      planner: null,
      persona: {},
      memory_citations: [],
      memory_used_count: 0,
      trust_log: null,
      ai_disclosure: "disclosure",
      regulation_notice: "notice",
    };

    expect(isDecideResponse(response)).toBe(true);
    expect(isEvoTips(response.evo)).toBe(true);
  });

  it("TrustLog.fuji accepts typed FujiDecision (OpenAPI $ref alignment)", () => {
    const fuji: FujiDecision = {
      status: "allow",
      reasons: ["safe content"],
      violations: [],
      rule_hit: null,
      severity: null,
      remediation_hint: null,
      risky_text_fragment: null,
    };
    const log: TrustLog = {
      request_id: "req-typed-fuji",
      created_at: "2026-03-10T00:00:00Z",
      sources: ["memory"],
      critics: [],
      checks: ["fuji"],
      approver: "system",
      fuji,
      sha256: "abc123",
      sha256_prev: null,
    };

    expect(log.fuji).toBeDefined();
    expect(isFujiDecision(log.fuji)).toBe(true);
  });

  // ============================
  // Backend ↔ Frontend consistency verification tests
  // ============================

  it("Context requires user_id and query (matches backend/OpenAPI required fields)", () => {
    const ctx: Context = {
      user_id: "u1",
      query: "What should I do?",
    };

    expect(ctx.user_id).toBe("u1");
    expect(ctx.query).toBe("What should I do?");
  });

  it("Context accepts all backend-defined optional fields", () => {
    const ctx: Context = {
      user_id: "u1",
      query: "test",
      session_id: "s1",
      goals: ["goal1"],
      constraints: ["c1"],
      tools_allowed: ["tool1"],
      time_horizon: "short",
      preferences: ["pref1"],
      response_style: "logic",
      telos_weights: { honesty: 0.8 },
      affect_hint: { mood: "neutral" },
    };

    expect(ctx.user_id).toBe("u1");
    expect(ctx.query).toBe("test");
    expect(ctx.session_id).toBe("s1");
    expect(ctx.time_horizon).toBe("short");
    expect(ctx.response_style).toBe("logic");
  });

  it("FujiDecision reasons/violations default to empty arrays (matches backend default_factory=list)", () => {
    // Backend FujiDecision has default_factory=list for reasons/violations.
    // Frontend type requires these as string[] (always present in responses).
    const decision: FujiDecision = {
      status: "allow",
      reasons: [],
      violations: [],
    };
    expect(decision.reasons).toEqual([]);
    expect(decision.violations).toEqual([]);
    expect(isFujiDecision(decision)).toBe(true);
  });

  it("GateOut modifications defaults to empty array (matches backend default_factory=list)", () => {
    // Backend Gate has default_factory=list for modifications.
    // Frontend GateOut type requires modifications as an array (always present).
    const gate = {
      risk: 0.0,
      telos_score: 0.0,
      decision_status: "allow" as const,
      modifications: [],
    };
    expect(gate.modifications).toEqual([]);
    expect(isGateOut(gate)).toBe(true);
  });

  it("DecideResponse default field values match backend schema defaults", () => {
    // Verify DecideResponse can be constructed with all backend default values.
    // This ensures the frontend type is compatible with a minimal backend response.
    const response: DecideResponse = {
      ok: true,
      error: null,
      request_id: "test-id",
      version: "veritas-api 1.x",
      chosen: {},
      alternatives: [],
      options: [],
      decision_status: "allow",
      rejection_reason: null,
      values: null,
      telos_score: 0.0,
      fuji: {},
      gate: {
        risk: 0.0,
        telos_score: 0.0,
        decision_status: "allow",
        modifications: [],
      },
      evidence: [],
      critique: [],
      debate: [],
      extras: {},
      reason: null,
      rsi_note: null,
      evo: null,
      meta: {},
      plan: null,
      planner: null,
      persona: {},
      memory_citations: [],
      memory_used_count: 0,
      trust_log: null,
      ai_disclosure: "This response was generated by an AI system (VERITAS OS).",
      regulation_notice: "Subject to EU AI Act Regulation (EU) 2024/1689.",
    };
    expect(isDecideResponse(response)).toBe(true);
    expect(response.ok).toBe(true);
    expect(response.telos_score).toBe(0.0);
    expect(response.decision_status).toBe("allow");
    expect(response.memory_used_count).toBe(0);
  });

  it("EvidenceItem.confidence is typed as number (backend clamps to 0.0–1.0)", () => {
    // Backend clamps confidence to [0.0, 1.0]. Frontend type is number.
    // This test verifies the type guard accepts valid confidence values.
    expect(isEvidenceItem({ source: "web", snippet: "text", confidence: 0.0 })).toBe(true);
    expect(isEvidenceItem({ source: "web", snippet: "text", confidence: 1.0 })).toBe(true);
    expect(isEvidenceItem({ source: "web", snippet: "text", confidence: 0.7 })).toBe(true);
  });

  it("DecideResponse.trust_log accepts TrustLog or generic object (matches backend Union type)", () => {
    // Backend: Optional[Union[TrustLog, Dict[str, Any]]]
    // Frontend: TrustLog | Record<string, unknown> | null
    const typedLog: TrustLog = {
      request_id: "req1",
      created_at: "2026-03-10T00:00:00Z",
      sources: [],
      critics: [],
      checks: [],
      approver: "system",
    };
    const response1: DecideResponse = {
      ok: true, error: null, request_id: "r1", version: "v1",
      chosen: {}, alternatives: [], options: [],
      decision_status: "allow", rejection_reason: null,
      values: null, telos_score: 0.0, fuji: {},
      gate: { risk: 0.0, telos_score: 0.0, decision_status: "allow", modifications: [] },
      evidence: [], critique: [], debate: [], extras: {},
      reason: null, rsi_note: null, evo: null, meta: {},
      plan: null, planner: null, persona: {},
      memory_citations: [], memory_used_count: 0,
      trust_log: typedLog,
      ai_disclosure: "d", regulation_notice: "r",
    };
    expect(isDecideResponse(response1)).toBe(true);

    // Also accepts a generic record
    const response2: DecideResponse = { ...response1, trust_log: { request_id: "req2", custom: true } };
    expect(isDecideResponse(response2)).toBe(true);

    // Also accepts null
    const response3: DecideResponse = { ...response1, trust_log: null };
    expect(isDecideResponse(response3)).toBe(true);
  });
});
