import { describe, expect, it } from "vitest";
import { isDecideResponse, isHealthResponse, isPersonaState, isEvoTips } from "./index";
import type {
  ChatRequest,
  CritiqueItem,
  DebateView,
  DecideResponse,
  EvoTips,
  FujiDecision,
  HealthResponse,
  MemoryKind,
  PersonaState,
  ResponseStyle,
  RetentionClass,
  TimeHorizon,
  TrustLog,
} from "./index";

describe("types", () => {
  it("accepts a valid health response shape", () => {
    const response: HealthResponse = {
      ok: true,
      uptime: 120,
      checks: {
        pipeline: "ok",
        memory: "ok",
      },
    };

    expect(response.ok).toBe(true);
  });

  it("validates health response payloads at runtime", () => {
    expect(
      isHealthResponse({
        ok: true,
        uptime: 120,
        checks: {
          pipeline: "ok",
          memory: "ok",
        },
      })
    ).toBe(true);

    expect(
      isHealthResponse({
        ok: true,
        uptime: "not-a-number",
        checks: {
          pipeline: "ok",
          memory: "ok",
        },
      })
    ).toBe(false);

    expect(
      isHealthResponse({
        ok: true,
        uptime: 120,
        checks: {
          pipeline: "ok",
        },
      })
    ).toBe(false);
  });

  it("accepts a backend-aligned decide response shape", () => {
    const response: DecideResponse = {
      ok: true,
      error: null,
      request_id: "req_123",
      version: "veritas-api 1.x",
      chosen: { id: "alt-1" },
      alternatives: [
        {
          id: "alt-1",
          title: "Option A",
          description: "A description",
          score: 0.9
        }
      ],
      options: [
        {
          id: "alt-1",
          title: "Option A",
          description: "A description",
          score: 0.9
        }
      ],
      decision_status: "allow",
      rejection_reason: null,
      values: {
        scores: { safety: 0.9 },
        total: 0.9,
        top_factors: ["safety"],
        rationale: "safe"
      },
      telos_score: 0.8,
      fuji: { status: "allow" },
      gate: {
        risk: 0.1,
        telos_score: 0.8,
        decision_status: "allow",
        modifications: []
      },
      evidence: [
        {
          source: "memory",
          snippet: "evidence",
          confidence: 0.7
        }
      ],
      critique: [],
      debate: [],
      extras: {},
      reason: null,
      rsi_note: null,
      evo: null,
      meta: {},
      plan: null,
      planner: null,
      persona: {},
      memory_citations: [],
      memory_used_count: 0,
      trust_log: null,
      ai_disclosure: "This content was generated by an AI system.",
      regulation_notice: "EU AI Act Art. 50 compliance notice."
    };

    expect(response.decision_status).toBe("allow");
  });

  it("validates decide response payloads at runtime", () => {
    const validPayload: DecideResponse = {
      ok: true,
      error: null,
      request_id: "req_123",
      version: "veritas-api 1.x",
      chosen: { id: "alt-1" },
      alternatives: [],
      options: [],
      decision_status: "allow",
      rejection_reason: null,
      values: null,
      telos_score: 0.8,
      fuji: {},
      gate: {
        risk: 0.1,
        telos_score: 0.8,
        decision_status: "allow",
        modifications: []
      },
      evidence: [],
      critique: [],
      debate: [],
      extras: {},
      reason: null,
      rsi_note: null,
      evo: null,
      meta: {},
      plan: null,
      planner: null,
      persona: {},
      memory_citations: [],
      memory_used_count: 0,
      trust_log: null,
      ai_disclosure: "This content was generated by an AI system.",
      regulation_notice: "EU AI Act Art. 50 compliance notice."
    };

    expect(isDecideResponse(validPayload)).toBe(true);

    expect(
      isDecideResponse({
        ...validPayload,
        decision_status: "unknown"
      })
    ).toBe(false);
  });

  it("TrustLog type includes sha256 field for hash-chain verification", () => {
    const log: TrustLog = {
      request_id: "req-1",
      created_at: "2026-02-12T00:00:00Z",
      sources: ["memory"],
      critics: [],
      checks: ["fuji"],
      approver: "system",
      sha256: "a".repeat(64),
      sha256_prev: "b".repeat(64),
    };

    expect(log.sha256).toBe("a".repeat(64));
    expect(log.sha256_prev).toBe("b".repeat(64));
  });

  it("CritiqueItem type matches backend CritiqueItem schema", () => {
    const item: CritiqueItem = {
      issue: "Potential bias detected",
      severity: "high",
      fix: "Add diverse training data",
    };

    expect(item.severity).toBe("high");
    expect(item.fix).toBe("Add diverse training data");
  });

  it("DebateView type matches backend DebateView schema", () => {
    const view: DebateView = {
      stance: "for",
      argument: "This approach maximizes safety",
      score: 0.85,
    };

    expect(view.score).toBe(0.85);
  });

  it("FujiDecision type matches backend FujiDecision schema", () => {
    const decision: FujiDecision = {
      status: "allow",
      reasons: ["safe content"],
      violations: [],
    };

    expect(decision.status).toBe("allow");
    expect(decision.violations).toHaveLength(0);
  });

  it("MemoryKind type matches backend VALID_MEMORY_KINDS", () => {
    const kinds: MemoryKind[] = ["semantic", "episodic", "skills", "doc", "plan"];
    expect(kinds).toHaveLength(5);
    expect(kinds).toContain("semantic");
    expect(kinds).toContain("plan");
  });

  it("TimeHorizon type matches backend Context.time_horizon", () => {
    const horizons: TimeHorizon[] = ["short", "mid", "long"];
    expect(horizons).toHaveLength(3);
  });

  it("ResponseStyle type matches backend Context.response_style", () => {
    const styles: ResponseStyle[] = ["logic", "emotional", "business", "expert", "casual"];
    expect(styles).toHaveLength(5);
  });

  it("RetentionClass type matches backend ALLOWED_RETENTION_CLASSES", () => {
    const classes: RetentionClass[] = ["short", "standard", "long", "regulated"];
    expect(classes).toHaveLength(4);
  });

  it("PersonaState type matches backend PersonaState schema", () => {
    const state: PersonaState = {
      name: "VERITAS",
      style: "direct, strategic, honest",
      tone: "warm",
      principles: ["honesty", "dignity", "growth"],
      last_updated: "2026-03-10T00:00:00Z",
    };

    expect(state.name).toBe("VERITAS");
    expect(state.principles).toHaveLength(3);
  });

  it("validates PersonaState payloads at runtime", () => {
    expect(
      isPersonaState({
        name: "VERITAS",
        style: "direct",
        tone: "warm",
        principles: ["honesty"],
      })
    ).toBe(true);

    expect(
      isPersonaState({
        name: "VERITAS",
        style: "direct",
        tone: "warm",
        principles: ["honesty"],
        last_updated: null,
      })
    ).toBe(true);

    expect(isPersonaState(null)).toBe(false);
    expect(isPersonaState({ name: "VERITAS" })).toBe(false);
    expect(
      isPersonaState({
        name: "VERITAS",
        style: "direct",
        tone: "warm",
        principles: [123],
      })
    ).toBe(false);
  });

  it("EvoTips type matches backend EvoTips schema", () => {
    const tips: EvoTips = {
      insights: { safety: "high" },
      actions: ["review policy"],
      next_prompts: ["consider edge cases"],
      notes: ["note 1"],
    };

    expect(tips.actions).toHaveLength(1);
    expect(tips.next_prompts).toHaveLength(1);
  });

  it("validates EvoTips payloads at runtime", () => {
    expect(
      isEvoTips({
        insights: {},
        actions: [],
        next_prompts: [],
        notes: [],
      })
    ).toBe(true);

    expect(isEvoTips(null)).toBe(false);
    expect(isEvoTips({ insights: {} })).toBe(false);
    expect(
      isEvoTips({
        insights: {},
        actions: [123],
        next_prompts: [],
        notes: [],
      })
    ).toBe(false);
  });

  it("ChatRequest type matches backend ChatRequest schema", () => {
    const req: ChatRequest = {
      message: "Hello, VERITAS",
      session_id: "sess_abc",
      memory_auto_put: true,
      persona_evolve: true,
    };

    expect(req.message).toBe("Hello, VERITAS");
  });

  it("ChatRequest accepts minimal required fields", () => {
    const req: ChatRequest = {
      message: "Hello",
    };

    expect(req.message).toBe("Hello");
    expect(req.session_id).toBeUndefined();
  });
});
