#!/usr/bin/env python3
"""Controlled CI-only TLS host for the native v2 sandbox event service.

This runner is deliberately not a production entrypoint. It starts the existing
independent sandbox ASGI service against a dedicated PostgreSQL database, using
synthetic writer/reader tokens supplied by the CI environment and a test
certificate generated by the workflow.

A filesystem flag can force read-only lookup requests to return 503. That flag is
used only for deterministic fault injection in the controlled composition proof;
it is not part of the product service API.
"""

from __future__ import annotations

import argparse
from datetime import UTC, datetime, timedelta
import os
from pathlib import Path

from fastapi import Request
from fastapi.responses import JSONResponse
from psycopg_pool import AsyncConnectionPool
from pydantic import SecretStr
import uvicorn

from veritas_os.policy.sandbox_event_service import (
    SandboxServiceTokens,
    create_sandbox_event_service,
)
from veritas_os.policy.sandbox_event_store import PostgresSandboxEventStore


def _dsn() -> str:
    value = os.environ.get("VERITAS_SANDBOX_DATABASE_URL", "").strip()
    if not value:
        raise RuntimeError("VERITAS_SANDBOX_DATABASE_URL is required")
    if value.startswith("postgresql+psycopg://"):
        value = value.replace("postgresql+psycopg://", "postgresql://", 1)
    return value


def _token(name: str) -> str:
    value = os.environ.get(name, "")
    if len(value) < 32:
        raise RuntimeError(f"{name} must contain a synthetic token of at least 32 characters")
    return value


def build_app() -> tuple[object, AsyncConnectionPool]:
    pool = AsyncConnectionPool(
        _dsn(),
        min_size=1,
        max_size=4,
        open=False,
    )
    store = PostgresSandboxEventStore(pool)
    tokens = SandboxServiceTokens(
        writer=SecretStr(_token("VERITAS_SANDBOX_WRITER_TOKEN")),
        reader=SecretStr(_token("VERITAS_SANDBOX_READER_TOKEN")),
        valid_until=datetime.now(UTC) + timedelta(hours=1),
    )
    app = create_sandbox_event_service(store=store, tokens=tokens)

    ddl = Path(__file__).resolve().parents[1] / "veritas_os" / "policy" / "sandbox_events.sql"

    async def startup() -> None:
        await pool.open(wait=True)
        async with pool.connection() as conn:
            await conn.execute(ddl.read_text())

    async def shutdown() -> None:
        await pool.close()

    app.add_event_handler("startup", startup)
    app.add_event_handler("shutdown", shutdown)

    outage_flag = os.environ.get("VERITAS_SANDBOX_LOOKUP_OUTAGE_FLAG", "").strip()

    @app.middleware("http")
    async def controlled_lookup_outage(request: Request, call_next):
        if (
            outage_flag
            and Path(outage_flag).exists()
            and request.method == "GET"
            and request.url.path.startswith("/v1/operations")
        ):
            return JSONResponse(
                {"detail": "CONTROLLED_LOOKUP_OUTAGE"},
                status_code=503,
                headers={"Cache-Control": "no-store"},
            )
        return await call_next(request)

    return app, pool


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--host", default="0.0.0.0")
    parser.add_argument("--port", type=int, default=443)
    parser.add_argument("--cert", required=True)
    parser.add_argument("--key", required=True)
    args = parser.parse_args()

    app, _pool = build_app()
    uvicorn.run(
        app,
        host=args.host,
        port=args.port,
        ssl_certfile=args.cert,
        ssl_keyfile=args.key,
        http="h11",
        access_log=False,
        server_header=False,
        log_level="warning",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
